{10}{}{Герой}
{11}{}{ }
{20}{}{Героиня}
{21}{}{ }
{30}{}{Деревенщина}
{40}{}{Деревенщина}
{50}{}{Рад-скорпион}
{51}{}{Небольшой мутировавший скорпион.}
{60}{}{Рад-скорпион}
{61}{}{Мутировавший скорпион}
{70}{}{Коготь Смерти}
{71}{}{Маленький Коготь Смерти}
{80}{}{Коготь Смерти}
{81}{}{Маленький Коготь Смерти}
{90}{}{Пес}
{91}{}{Собака, наверняка бездомная, дворняжьей породы.}
{100}{}{Брамин}
{101}{}{Двухголовая корова-мутант.}
{110}{}{Грызун}
{111}{}{Самый обыкновенный большой грызун.}
{120}{}{Мантис}
{121}{}{Страшно надоедливое существо.}
{130}{}{Старейшая}
{140}{}{Хакунин}
{150}{}{Минок}
{160}{}{Хищный Цветок}
{161}{}{Плотоядное растение.}
{170}{}{Симпатичный раб}
{180}{}{Красивый раб}
{190}{}{Здоровая рабыня}
{200}{}{Здоровый раб}
{210}{}{Сильная рабыня}
{220}{}{Сильный раб}
{230}{}{Боевая рабыня}
{240}{}{Боевой раб}
{250}{}{Умная рабыня}
{260}{}{Умный раб}
{270}{}{Обычная рабыня}
{280}{}{Обычный раб}
{290}{}{Анна}
{300}{}{Крутой бандит}
{310}{}{Крутая воровка}
{320}{}{Жестокий бандит}
{330}{}{Лихая разбойница}
{340}{}{Проворный бандит}
{350}{}{Ловкая потаскуха}
{360}{}{Мощный бандит}
{370}{}{Стерва с пушкой}
{380}{}{Бандит с пушкой}
{390}{}{Дешевая шлюха}
{400}{}{Крутой Охранник}
{410}{}{Крутая Охранница}
{420}{}{Мощный Охранник}
{430}{}{Мощная Охранница}
{440}{}{Ловкий Охранник}
{450}{}{Ловкая Охранница}
{460}{}{Охранник со стволом}
{470}{}{Охранница со стволом}
{480}{}{Охранник с пушкой}
{490}{}{Охранница с пушкой}
{500}{}{Сирота}
{510}{}{Сирота}
{520}{}{Ребенок}
{530}{}{Ребенок}
{540}{}{Нищий}
{550}{}{Нищенка}
{560}{}{Плохой торговец}
{570}{}{Плохая торговка}
{580}{}{Обычный продавец}
{590}{}{Обычная продавщица}
{600}{}{Мастер-купец}
{610}{}{Мастерица-купчиха}
{620}{}{Вик}
{630}{}{Слабый крестьянин}
{640}{}{Слабая крестьянка}
{650}{}{Обычный крестьянин}
{660}{}{Обычная крестьянка}
{670}{}{Сильный крестьянин}
{680}{}{Сильная крестьянка}
{690}{}{Слабый охранник}
{700}{}{Слабая охранница}
{710}{}{Слабый стрелок}
{720}{}{Слабая снайперша}
{730}{}{Робот-ремонтник}
{740}{}{Робот-ремонтник тип 2}
{750}{}{Робомозг}
{760}{}{Летучий Глаз}
{770}{}{Робот-страж}
{780}{}{Робот-страж тип 2}
{790}{}{Робомозг}
{800}{}{Мелкий ящер}
{810}{}{Крутой ящерок}
{820}{}{Волк}
{821}{}{Жестокое и свирепое хищное животное.}
{830}{}{Золотой ящер}
{840}{}{Коготь Смерти}
{850}{}{Отродье Когтя Смерти}
{860}{}{Сильный Золотой ящер}
{870}{}{Линетта}
{880}{}{Доктор Трой}
{890}{}{Джон Кэссиди}
{900}{}{Грегори}
{910}{}{Гражданка}
{920}{}{Гражданин}
{930}{}{Богатая гражданка}
{940}{}{Богатый гражданин}
{950}{}{Траппер}
{960}{}{Траппер}
{970}{}{Сулик}
{980}{}{Майда Бакнер}
{990}{}{Торр}
{1000}{}{Лумпи}
{1010}{}{Светящийся призрак}
{1020}{}{Призрак реактора}
{1030}{}{Стражник реактора}
{1040}{}{Зомак}
{1050}{}{Скитер}
{1060}{}{Крысиный Мозг}
{1070}{}{Ленни}
{1080}{}{Вузи}
{1090}{}{Гарольд}
{1100}{}{Крот-гризли}
{1110}{}{Большой крот-гризли}
{1120}{}{Крысокабан}
{1130}{}{Свирепый крысокабан}
{1140}{}{Слабый брамин}
{1141}{}{Мутировавшая двухголовая корова.}
{1150}{}{A.Pwr.Armor (don't use)}
{1160}{}{Крыса-мутант}
{1161}{}{Мутировавшая от радиации крыса.}
{1170}{}{Мутировавший крот-гризли}
{1171}{}{Покрутевший и злой крот-гризли.}
{1180}{}{Мутировавший крысокабан}
{1181}{}{Сильно оголодавший от мутации монстр.}
{1190}{}{Супер Мутант}
{1200}{}{Накачанный мутант}
{1210}{}{Мельхиор}
{1220}{}{Нero Andro (don't use)}
{1230}{}{Нero Andro (don't use)}
{1240}{}{Нero Male (don't use)}
{1250}{}{Нero Female (don't use)}
{1260}{}{Нero Male (don't use)}
{1270}{}{Нero Female (don't use)}
{1280}{}{Нero Male (don't use)}
{1290}{}{Нero Female (don't use)}
{1300}{}{Нero Male (don't use)}
{1310}{}{Нero Female (don't use)}
{1320}{}{Нero Male (don't use)}
{1330}{}{Нero Female (don't use)}
{1340}{}{Гвардеец Города}
{1350}{}{Гвардеец Города}
{1360}{}{Кибердог}
{1370}{}{Стражник НКР}
{1380}{}{Стражник НКР}
{1390}{}{Полицейский НКР}
{1400}{}{Сторож рабов}
{1410}{}{Надсмотрщик}
{1420}{}{Великий торговец людьми}
{1430}{}{Великая торговка людьми}
{1440}{}{Танди}
{1450}{}{Мерк}
{1460}{}{Ратч}
{1470}{}{Скитер}
{1480}{}{Майки}
{1490}{}{Бармен НКР}
{1500}{}{Владелец магазина}
{1510}{}{Грунтар}
{1520}{}{Горис}
{1530}{}{Хищный крот-гризли}
{1540}{}{Хищный крот-гризли}
{1550}{}{Хищный крот-гризли}
{1560}{}{Хищный крот-гризли}
{1570}{}{Хищный крот-гризли}
{1580}{}{Хищный крот-гризли}
{1590}{}{Обычный призрак}
{1600}{}{Мирон}
{1610}{}{Маркус}
{1620}{}{Доктор Джонс}
{1630}{}{Дэвин}
{1640}{}{Мирия}
{1650}{}{Лэдди}
{1660}{}{Рондо}
{1670}{}{Подмастерье}
{1680}{}{Подмастерье}
{1690}{}{Подмастерье}
{1700}{}{Вышибала}
{1710}{}{Вышибала}
{1720}{}{Слабый мр. Хэнди}
{1730}{}{Обычный Светящийся}
{1740}{}{Дар}
{1750}{}{Далиа}
{1760}{}{Гордон}
{1770}{}{test (don't use)}
{1780}{}{Призрак реактора}
{1790}{}{Обычный призрак}
{1800}{}{Мэтт}
{1810}{}{Командир охотников}
{1820}{}{Охотник за бандитами}
{1830}{}{Командир охотников}
{1840}{}{Охотник за бандитами}
{1850}{}{Охотник за бандитами}
{1860}{}{Командир охотников}
{1870}{}{Охотник за бандитами}
{1880}{}{Охотник за бандитами}
{1890}{}{Командир охотников}
{1900}{}{Охотник за бандитами}
{1910}{}{Бесс}
{1911}{}{Двухголовая мутировавшая корова.}
{1920}{}{Балтас}
{1930}{}{Гришэм}
{1940}{}{Фил}
{1950}{}{Цыпленок}
{1960}{}{Карл}
{1970}{}{Джонни}
{1980}{}{Джо}
{1990}{}{Зеке}
{2000}{}{Мясник}
{2010}{}{Питти}
{2020}{}{Воин племени}
{2030}{}{Воительница племени}
{2040}{}{Каннибал}
{2050}{}{Людоедка}
{2060}{}{Святой муж}
{2070}{}{Святая женщина}
{2080}{}{Кочевник}
{2090}{}{Кочевник}
{2100}{}{Кочевница}
{2110}{}{Кочевница}
{2120}{}{Убийца}
{2130}{}{Убийца}
{2140}{}{Крестьянин}
{2150}{}{Крестьянка}
{2160}{}{Мантис}
{2170}{}{Рабовладелец}
{2180}{}{Рабовладелица}
{2190}{}{Дикий брамин}
{2200}{}{Переселенец}
{2210}{}{Переселенка}
{2220}{}{Патрульный Города}
{2230}{}{Патрульная Города}
{2240}{}{Сильный рабовладелец}
{2250}{}{Сильная рабовладелица}
{2260}{}{Чокнутый}
{2270}{}{Мародер}
{2280}{}{Чокнутый из Глоу}
{2290}{}{Мародер из Глоу}
{2300}{}{Рыбак}
{2310}{}{Рыбачка}
{2320}{}{Дикарь}
{2330}{}{Дикарка}
{2340}{}{Самогонщик}
{2350}{}{Самогонщица}
{2360}{}{Артельщик}
{2370}{}{Артельщица}
{2380}{}{Рейдер}
{2390}{}{Рейдерша}
{2400}{}{Огнедышащий ящер}
{2410}{}{Крутой огнедышащий ящер}
{2420}{}{Инопланетянин}
{2430}{}{Чужой}
{2440}{}{Мелкий сильный Коготь Смерти}
{2450}{}{Злобный Коготь Смерти}
{2460}{}{Летатель}
{2470}{}{Подлый Летатель}
{2480}{}{Псевдо-кентавр}
{2490}{}{Кентавр Апдайка}
{2500}{}{Патрульный АНКЛАВА}
{2510}{}{Патрульная АНКЛАВА}
{2520}{}{Саботажник}
{2530}{}{Саботажница}
{2540}{}{Наемник}
{2550}{}{Наемница}
{2560}{}{Найткин}
{2570}{}{Мощный Найткин}
{2580}{}{Крутой Призрак}
{2590}{}{Мафиози}
{2600}{}{Якудза}
{2610}{}{Рейнджер НКР}
{2620}{}{Рейнджер НКР}
{2630}{}{Мародер}
{2640}{}{Мародер}
{2650}{}{Симпатяга Ллойд}
{2660}{}{Зубастый грызун}
{2670}{}{Житель 13-го}
{2680}{}{Жительница 13-го}
{2690}{}{Хранитель Моста}
{2700}{}{Таинственный незнакомец}
{2710}{}{Таинственная незнакомка}
{2720}{}{Хэйксвилл}
{2730}{}{Большой Езус Мордино}
{2740}{}{Думар}
{2750}{}{Мать Когтей Смерти}
{2760}{}{Дракон}
{2770}{}{Ло Пан}
{2780}{}{Хабологист}
{2790}{}{Хабологистка}
{2800}{}{Неопознанная личность}
{2810}{}{Неопознанная личность}
{2820}{}{Неопознанная личность}
{2830}{}{Неопознанная личность}
{2840}{}{Неопознанная личность}
{2850}{}{Неопознанная личность}
{2860}{}{Неопознанная личность}
{2870}{}{Неопознанная личность}
{2880}{}{Суперагент Президента}
{2890}{}{Яйцо Когтя Смерти}
{2900}{}{Метцгер}
{2910}{}{Гвардеец АНКЛАВА}
{2920}{}{Гвардеец АНКЛАВА}
{2930}{}{Президент}
{2940}{}{Вице-президент}
{2950}{}{Техник}
{2960}{}{Бадгер}
{2970}{}{Доктор Фонг}
{2980}{}{Дитя}
{2990}{}{Дитя}
{3000}{}{Продавец оружия}
{3010}{}{Лаборант Ши}
{3020}{}{Страж Ши}
{3030}{}{Крестьянин Ши}
{3040}{}{Крестьянка Ши}
{3050}{}{Крестьянин Ло Пана}
{3060}{}{Крестьянка Ло Пана}
{3070}{}{Докер}
{3080}{}{Торговец Ши}
{3090}{}{Пинки}
{3100}{}{Сулик - Стадия 1}
{3110}{}{Сулик - Стадия 2}
{3120}{}{Сулик - Стадия 3}
{3130}{}{Сулик - Стадия 4}
{3140}{}{Сулик - Стадия 5}
{3150}{}{Сулик - Стадия 6}
{3160}{}{Ленни - Стадия 1}
{3170}{}{Ленни - Стадия 2}
{3180}{}{Ленни - Стадия 3}
{3190}{}{Горис - Стадия 1}
{3200}{}{Горис - Стадия 2}
{3210}{}{Горис - Стадия 3}
{3220}{}{Горис - Стадия 4}
{3230}{}{Горис - Стадия 5}
{3240}{}{Горис - Стадия 6}
{3250}{}{Мирон - Стадия 1}
{3260}{}{Мирон - Стадия 2}
{3270}{}{Мирон - Стадия 3}
{3280}{}{Мирон - Стадия 4}
{3290}{}{Маркус - Стадия 1}
{3300}{}{Маркус - Стадия 2}
{3310}{}{Маркус - Стадия 3}
{3320}{}{Маркус - Стадия 4}
{3330}{}{Маркус - Стадия 5}
{3340}{}{Кибердог - Стадия 1}
{3350}{}{Кибердог - Стадия 2}
{3360}{}{Кибердог - Стадия 3}
{3370}{}{Кибердог - Стадия 4}
{3380}{}{Кэссиди - Стадия 1}
{3390}{}{Кэссиди - Стадия 2}
{3400}{}{Кэссиди - Стадия 3}
{3410}{}{Кэссиди - Стадия 4}
{3420}{}{Догмит}
{3430}{}{Догмит - Стадия 1}
{3440}{}{Догмит - Стадия 2}
{3450}{}{Догмит - Стадия 3}
{3460}{}{Догмит - Стадия 4}
{3470}{}{Догмит - Стадия 5}
{3480}{}{Догмит - Стадия 6}
{3490}{}{Робомозг - Стадия 1}
{3500}{}{Робомозг - Стадия 2}
{3510}{}{Робомозг - Стадия 3}
{3520}{}{Робомозг - Стадия 4}
{3530}{}{Робомозг - Стадия 5}
{3540}{}{Инопланетное существо}
{3550}{}{Черный Рад-скорпион}
{3560}{}{Черный Рад-скорпион}
{3570}{}{Спад}
{3580}{}{Капитан рейдеров}
{3590}{}{Рейдер}
{3600}{}{Рейдер}
{3610}{}{Тень-что-бродит}
{3620}{}{Панк}
{3630}{}{Панк}
{3640}{}{Марк}
{3650}{}{Дэйв Х.}
{3660}{}{Капитан Арон Мейерс}
{3670}{}{Чип}
{3680}{}{АХС-9}
{3690}{}{Стражник хабологистов}
{3700}{}{Стражница хабологистов}
{3710}{}{Хуан}
{3720}{}{Викки}
{3730}{}{Вик - Стадия 1}
{3740}{}{Вик - Стадия 2}
{3750}{}{Вик - Стадия 3}
{3760}{}{Вик - Стадия 4}
{3770}{}{Вик - Стадия 5}
{3780}{}{Вик - Стадия 6}
{3790}{}{Робомозг - Шимпанзе}
{3800}{}{Робомозг - Ненормальный}
{3810}{}{Робомозг - Человек}
{3820}{}{Муравей}
{3830}{}{Крутой муравей}
{3840}{}{Пария}
{3850}{}{Зурак}
{3860}{}{Имбот}
{3870}{}{Джимми}
{3880}{}{Вейунгх}
{3890}{}{Херб}
{3900}{}{Лупал}
{3910}{}{Джобе}
{3920}{}{Смитти}
{3930}{}{Рубе}
{3940}{}{Мастер Кралл}
{3950}{}{Зигги}
{3960}{}{Мастер Кунг}
{3970}{}{Джон Бишоп}
{3980}{}{Анжела Бишоп}
{3990}{}{Миссис Бишоп}
{4000}{}{Телохранитель 1}
{4010}{}{Телохранитель 2}
{4020}{}{Громила Бишопа 1}
{4030}{}{Громила Бишопа 2}
{4040}{}{Сердитый брамин}
{4050}{}{Малый Езус}
{4060}{}{Большой Езус}
{4070}{}{Человек Мордино 1}
{4080}{}{Человек Мордино 2}
{4090}{}{Человек Мордино 3}
{4100}{}{Телохранитель Мирона 1}
{4110}{}{Телохранитель Мирона 2}
{4120}{}{Мистер Врайт}
{4130}{}{Миссис Врайт}
{4140}{}{Крис Врайт}
{4150}{}{Кейт Врайт}
{4160}{}{Сын Врайта 1}
{4170}{}{Сын Врайта 2}
{4180}{}{Дочь Врайта 1}
{4190}{}{Дочь Врайта 2}
{4200}{}{Мистер Сальваторе}
{4210}{}{Мэйсон}
{4220}{}{Вышибала Сальваторе 1}
{4230}{}{Вышибала Сальваторе 2}
{4240}{}{Обычный бармен 1}
{4250}{}{Обычный бармен 2}
{4260}{}{Обычный бармен 3}
{4270}{}{Боксер 1}
{4280}{}{Боксер 2}
{4290}{}{Боксер 3}
{4300}{}{Боксер 4}
{4310}{}{Майк Мастикатор}
{4320}{}{Холифелд}
{4330}{}{МакКнили}
{4340}{}{Малыш Стюарт}
{4350}{}{Братья с Корсики}
{4360}{}{Порноактрисы}
{4370}{}{Отец Тулли}
{4380}{}{Вышибала Казино 1}
{4390}{}{Вышибала Казино 2}
{4400}{}{Крупье}
{4410}{}{Сутенер/Наркоторговец1}
{4420}{}{Сутенер/Наркоторговец1}
{4430}{}{Сутенер/Наркоторговец1}
{4440}{}{Сутенер/Наркоторговец1}
{4450}{}{МакГи}
{4460}{}{Мисс Китти}
{4470}{}{Обычная Шлюха 1}
{4480}{}{Обычная Шлюха 2}
{4490}{}{Джимми Джей}
{4500}{}{Ренеско}
{4510}{}{Ученый}
{4520}{}{Элдридж}
{4530}{}{Алжернон}
{4540}{}{Джулс}
{4550}{}{Бюрократ 1}
{4560}{}{Бюрократ 2}
{4570}{}{Продавец 1}
{4580}{}{Продавец 2}
{4590}{}{Охранник 1}
{4600}{}{Охранник 2}
{4610}{}{Охранник 3}
{4620}{}{Охранник 4}
{4630}{}{Солдат 1}
{4640}{}{Солдат 2}
{4650}{}{Солдат 3}
{4660}{}{Солдат 4}
{4670}{}{Сержант Старк}
{4680}{}{Доктор Эндрью}
{4690}{}{Бармен}
{4700}{}{Орудийная башня}
{4701}{}{Автоматическое оборонительное устройство, снабженное двумя плазма-пушками.}
{4710}{}{К-9 (базовый)}
{4720}{}{К-9 (стадия 1)}
{4730}{}{К-9 (стадия 2)}
{4740}{}{К-9 (стадия 3)}
{4750}{}{К-9 (стадия 4)}
{4760}{}{Обычный Кибердог}
{4770}{}{Яйцо Ванаминго}
{4780}{}{Страж Ло Пана}
{4790}{}{Мэрджори}
{4800}{}{Авто-пушка}
{4810}{}{Особенный ящер}
{4820}{}{Смертушка}
{4830}{}{Фрэнк Хорриган}
{4831}{}{Суперагент и телохранитель президента}
{4840}{}{Хаболог}
{4850}{}{Хаболог}
{4860}{}{Паладин Братства}
{4870}{}{Гигантская оса}
{4880}{}{Жук-мутант}
{4890}{}{Мятежник}
{4900}{}{Опасный жук}
{4910}{}{Инженер}
{4920}{}{Пехотинец Анклава}
{4930}{}{Инженер}
{4940}{}{Солдат Братства}
{4950}{}{Диверсант}
{4960}{}{Солдат Анклава}
{4970}{}{Паладин Братства}
{4980}{}{Патрульный регулятор}
{4990}{}{Бандит}
{5000}{}{Разбойница}
{5010}{}{Рейдер}
{5020}{}{Рейдер}
{5030}{}{Рейдер}
{5040}{}{Рейдер}
{5050}{}{Гигантская оса}
{5051}{}{Огромное кровожадное насекомое}
{5060}{}{Гвардеец}
{5061}{}{Боец Гвардии ГУ}
{5061}{}{Гвардеец}
{5061}{}{Рядовой гвардеец}
{5070}{}{Летучая мышь}
{5080}{}{Патрульный Арройо}
{5090}{}{Патрульный Арройо}
{5100}{}{Патрульный Арройо}
{5110}{}{Беглец}
{5120}{}{Беглец}
{5130}{}{Беглец}
{5140}{}{Беглец}
{5150}{}{Беглец}
{5160}{}{Илай}
{5170}{}{Чемпион}
{5180}{}{Хелацитон тип 1}
{5181}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5190}{}{Злобный хелацитон тип 1}
{5191}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5200}{}{Хелацитон тип 2}
{5201}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5210}{}{Злобный хелацитон тип 2}
{5211}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5220}{}{Хелацитон тип 3}
{5221}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5230}{}{Генриетта}
{5231}{}{Кожа этого существа напоминает одну большую мозоль.}
{5240}{}{Андроид}
{5250}{}{Тим Кейн}
{5260}{}{Шакал Карлоса}
{5261}{}{Вы видите хладнокровного бандита. Он состоит в шайке Рамиреса Карлоса под названием Шакалы.}
{5270}{}{Шакал Карлоса}
{5271}{}{Головорез из банды Шакалы Карлоса.}
{5271}{}{Человек Рамиреса Карлоса. Шакалы - немногочисленная банда, но даже поодиночке представляют серьезную угрозу.}
{5280}{}{Бегемот}
{5281}{}{Огромный механический жук на шести лапах, оснащен крупнокалиберным пулеметом.}
{5290}{}{Гуль-репликант}