# 08.2007 Cvet

# Version info
{1}{}{FOnline: The Life After v0.11}

####################################################################################################################################
#
#		Months, Day of week
#
####################################################################################################################################

{21}{}{Январь}
{22}{}{Февраль}
{23}{}{Март}
{24}{}{Апрель}
{25}{}{Май}
{26}{}{Июнь}
{27}{}{Июль}
{28}{}{Август}
{29}{}{Сентябрь}
{30}{}{Октябрь}
{31}{}{Ноябрь}
{32}{}{Декабрь}

{33}{}{Воскресенье}
{34}{}{Понедельник}
{35}{}{Вторник}
{36}{}{Среда}
{37}{}{Четверг}
{38}{}{Пятница}
{39}{}{Суббота}

####################################################################################################################################
#
#		Material Types (from PROTO.MSG)
#
####################################################################################################################################

{40}{}{Стекло}
{41}{}{Металл}
{42}{}{Пластик}
{43}{}{Дерево}
{44}{}{Грязь}
{45}{}{Камень}
{46}{}{Цемент}
{47}{}{Кожа}

####################################################################################################################################
#
#		Misc
#
####################################################################################################################################

{50}{}{.}
{52}{}{,}
{53}{}{ }
{54}{}{ и }
{55}{}{ или }

####################################################################################################################################
#
#		Music/Video
#
####################################################################################################################################

# Main theme
{80}{}{01 - No Fate No Fear.ogg}
# Intro, from 90 to 99
{90}{}{TheLifeAfterIntro.ogv|TheLifeAfterIntro.ogg}
{91}{}{TheLifeAfterIntroSlide.ogv|TheLifeAfterIntroSlideRU.ogg}

####################################################################################################################################
#
#		Chat
#
####################################################################################################################################

# On head messages
{100}{}{|0xF8F993 %s}                     # Normal
{102}{}{|0xFF0000 !!!%s!!!}               # Shout
{104}{}{|0xFF00FF **%s**}                 # Emote
{106}{}{|0x00FFFF ...%s...}               # Whisp
{108}{}{|0xFFFFFF %s}                     # Social

# Message box
{120}{}{%s: |0xF8F993 %s}                 # Normal
{122}{}{%s: |0xFF0000 !!!%s!!!}           # Shout
{124}{}{%s: |0xFF00FF **%s**}             # Emote
{126}{}{%s: |0x00FFFF ...%s...}           # Whisp
{128}{}{%s: |0xFFFFFF %s}                 # Social
{130}{}{Рация %u> |0xFFFFFE ..%s..}       # Radio
{132}{}{%s}                               # NetMsg

####################################################################################################################################
#
#		FixBoy
#
####################################################################################################################################

{200}{}{Параметры:}
{201}{}{Инструменты:}
{202}{}{Предметы:}
{205}{}{шт.}
{206}{}{у вас }
{210}{}{Вы успешно создали предмет (ы).}
{211}{}{Вам не удалось создать предмет (ы).}
{212}{}{Вы слишком устали, попробуйте повторить попытку позже.}

####################################################################################################################################
#
#		Interface text
#
####################################################################################################################################

{250}{}{|4291317840 Эта функция сейчас недоступна, используйте FOConfig.exe или Launcher.exe для редактирования настроек игры.}
{251}{}{Скриншот сохранен.}
{252}{}{Не удалось сохранить скриншот.}
{253}{}{Лог сохранен.}
{254}{}{Не удалось сохранить лог.}

{260}{}{Масштаб %d %%}
{265}{}{Игра приостановлена}

# Dialog
{275}{}{Бартер}
{276}{}{Сказать}
{277}{}{Лог}
# Barter
{280}{}{Обмен}
{281}{}{Диалог}
{282}{}{Выйти}
{283}{}{Сказать}
# Menu
{290}{}{Сохранить}   # Singleplayer
{291}{}{Загрузить}   # Singleplayer
{292}{}{Опции}
{293}{}{Выход}
{294}{}{Продолжить}
# Login
{300}{}{|0xAECF45 Новая игра}  # Singleplayer
{301}{}{|0xAECF45 Загрузить}   # Singleplayer
{302}{}{|0xAECF45 Играть}      # Multiplayer
{303}{}{|0xAECF45 Регистрация} # Multiplayer
{304}{}{|0xAECF45 Опции}
{305}{}{|0xAECF45 Авторы}
{306}{}{|0xAECF45 Выход}
# Dialog box
{310}{}{Отмена}
{311}{}{Дальше}
{312}{}{Следовать}
{313}{}{Открытый режим}
{314}{}{Скрытый режим}
{315}{}{Реальное время}
{316}{}{Пошаговый режим}
# Reg name
{320}{}{Имя}
{321}{}{Пароль}
# Cha
{325}{}{Далее}
{326}{}{Назад}
{327}{}{Печать}
{328}{}{Навыки}
{329}{}{Очки умений}
# Reg
{335}{}{Особые навыки}
{336}{}{Очки расп.}
# Perk
{340}{}{Взять}
{341}{}{Назад}
# Global map
{350}{}{Вы не можете управлять группой.}
{351}{}{Координаты: %d : %d\nЗона: %d : %d}
{352}{}{Координаты: %d : %d\nЗона: %d : %d\n%s\n%s}
{353}{}{%s\n%s}
# Aim
{360}{}{Цель заблокирована.}
# Split
{365}{}{Переместить}
{366}{}{Все}
# Timer
{370}{}{Таймер}
# Say screen
{375}{}{Далее}
{376}{}{Назад}
{377}{}{Сказать...}
# Input box
{380}{}{Запись}
{381}{}{Назад}
# Town view
{385}{}{Назад}
{386}{}{Войти}
{387}{}{Контуры}
# Save/Load
{390}{}{Сохранить}
{391}{}{Загрузить}
{392}{}{Далее}
{393}{}{Назад}
{394}{}{Новая запись}
{395}{}{Введите имя записи}

####################################################################################################################################
#
#		Inventory (with INVENTRY.MSG + 400)
#
####################################################################################################################################

{400}{}{СЛ}
{401}{}{ВС}
{402}{}{ВН}
{403}{}{ОБ}
{404}{}{ИН}
{405}{}{ЛВ}
{406}{}{УД}
{407}{}{Жизней}
{408}{}{Класс брони }
{409}{}{  Норма}
{410}{}{  Лазер}
{411}{}{  Огонь}
{412}{}{  Плазма}
{413}{}{  Взрыв}
{414}{}{Нет вещи}
{415}{}{Повр:}
{416}{}{Длн:}
{417}{}{Заряд:}
{418}{}{(Не одето)}
{419}{}{У вас не хватает Очков действия для входа в инвентарь.}
{420}{}{  Общий вес:}
{421}{}{ПЕРЕМЕСТИТЬ}
{422}{}{ВСЕ}
{423}{}{ТАЙМЕР}
{424}{}{Безоружно:}
{425}{}{Вы не можете подобрать эту вещь. Вы и так несете максимальный груз.}
{426}{}{Для этой вещи не хватает места.}
{429}{}{За удачное применение умения воровать, вы получаете %d очков опыта.}
{430}{}{Вес}
{433}{}{Вы не находите там ничего для себя полезного.}
{434}{}{Имеется VALUE/MAX_VALUE зарядов - AMMO.}
{435}{}{Вес: VALUE грамм.}
{436}{}{Вес: VALUE фунтов.}
{437}{}{Цена: VALUE монет.}
{438}{}{Цена у торговца: VALUE монет.}
{440}{}{Перегруз}
{441}{}{Скрытность}
{442}{}{Уровень}
{443}{}{Отравление}
{444}{}{Облучение}
{445}{}{Травмирован}
{446}{}{Привыкание}
{447}{}{Таймаут VALUE}
{448}{}{Негабаритный}
{449}{}{Ваш ход VALUE}
{450}{}{Пошагово}

####################################################################################################################################
#
#		Radio
#
####################################################################################################################################

{455}{}{Рация}
{456}{}{Канал}
{457}{}{Обновить}
{458}{}{Передача}
{459}{}{Приём}
{460}{}{Везде}
{461}{}{5 зон}
{462}{}{2 зоны}
{463}{}{Локация}
{464}{}{Карта}
{465}{}{Радиовещание включено.}
{466}{}{Радиовещание закончено.}
{467}{}{Радиовещание изменено.}
{468}{}{Радиоприём включён.}
{469}{}{Радиоприём закончен.}
{470}{}{Радиоприём изменён.}
{471}{}{Канал сменён.}
{474}{}{Невозможно переключить канал.}
{475}{}{Невозможно переключить передачу.}
{476}{}{Невозможно переключить приём.}
{477}{}{Невозможно переключить тип передачи.}
{478}{}{Невозможно переключить тип приёма.}
{479}{}{У вас нет радио настроенного на передачу.}

####################################################################################################################################
#
#		Barter
#
####################################################################################################################################

{480}{}{Ну хорошо, будь по вашему.}
{481}{}{Нет, ваше предложение меня не радует.}
{482}{}{Извините, для вас это уже слишком.}
{483}{}{Извините, но столько вам не унести.}
{484}{}{На момент продажи у вас не было выбранной вещи.}
{485}{}{Извини, но я уже продал кое-что из того, что ты выбрал.}
{486}{}{Вы не можете торговать в данный момент.}
{487}{}{Вы не можете торговать с этим персонажем.}
{490}{}{%s хочет поторговать с вами. Режим торговли: %s.}
{491}{}{открытый}
{492}{}{скрытный}
{493}{}{Игрок не может сейчас торговать с вами.}
{495}{}{Начата торговля с %s. Ваш режим: %s, режим оппонента: %s.}
{496}{}{%s готов к сделке.}
{497}{}{Персонаж торгует только за наличные.}
{498}{}{Товар не интересует этого персонажа.}

####################################################################################################################################
#
#		Items info
#
####################################################################################################################################

# Wear
{500}{}{Износ: VALUE%.}
{501}{}{Пройдено сервисное обслуживание.}
{502}{}{Пройдено дополнительное сервисное обслуживание.}
{503}{}{Небольшая поломка.}
{504}{}{Поломка средней тяжести.}
{505}{}{Серьезная поломка.}
{506}{}{Восстановлению не подлежит.}
{507}{}{Ломался: VALUE раз.}

{510}{}{Сервисное обслуживание уже пройдено.}
{511}{}{Сервисное обслуживание пройдено успешно.}
{512}{}{Сервисное обслуживание провалено.}
{515}{}{Ремонт произведен успешно.}
{516}{}{Ремонт провален.}

{520}{}{Ваша броня сломалась.}
{521}{}{Ваше оружие сломалось.}

# Key
{550}{}{Ключ номер KEY_ID.}

# Car
{560}{}{Номер машины CAR_ID.}
{561}{}{Топливо: VALUE/MAX_VALUE.}
{562}{}{Износ: VALUE%.}

####################################################################################################################################
#
#		PipBoy, Timeouts
#
####################################################################################################################################

{700}{}{----- Статус -----}
{701}{}{Баланс репликации}
{702}{}{%d монет}
{703}{}{Стоимость репликации}
{704}{}{%d монет}
{705}{}{Всего репликаций}
{706}{}{%d раз}
{720}{}{----- Квесты -----}
{723}{}{<<<<< Статистика >>>>>}
{725}{}{----- Карты -----}
{730}{}{----- Инфо -----}

{740}{}{----- Таймауты -----}
{741}{}{%s секунд}
{742}{}{%s минут}
{790}{}{Таймаут на переходы. Ждите.}
{791}{}{Боевой таймаут. Ждите.}
{792}{}{Таймаут на скрытность. Ждите.}

{795}{}{Информация в процессе загрузки...}
{796}{}{Ошибка загрузки! Пожалуйста перезагрузите PipBoy.}

####################################################################################################################################
#
#		Dialogs
#
####################################################################################################################################

{800}{}{Вы не можете говорить с мобом.}
{801}{}{Нпц не в состоянии сейчас говорить.}
{802}{}{Нпц занят. Попробуйте поговорить позже.}
{803}{}{Слишком большая дистанция для разговора.}
{804}{}{Привет.} # Нет диалогов.
{805}{}{Нпц разговаривает с другими игроками. Попробуйте поговорить позже.}
{806}{}{Ошибка преддиалоговых настроек.}
{807}{}{Битая ссылка диалога.}
{808}{}{Ошибка компановки диалога.}
{809}{}{Нпц не найден.}
{810}{}{Не валидный указатель на диалог.}

####################################################################################################################################
#
#		Global map
#
####################################################################################################################################

{900}{}{Вы не нашли локацию, ее поглотила пустошь.}
{901}{}{Локация странным образом переместилась в другое место.}
{902}{}{Вы не нашли входа в локацию.}
{903}{}{Вы не нашли стоянки для своего транспорта.}
{904}{}{Локация переполнена, попробуйте войти позже.}
{950}{}{Вы готовы следовать за %s в %s?}
{952}{}{Приготовьтесь следовать за %s в %s.}
{970}{}{незнакомцем}
{972}{}{пустошь}

####################################################################################################################################
#
#		Maintenance
#
####################################################################################################################################

{1001}{}{|4291317840 Введен неверный логин.}
{1002}{}{|4291317840 Введен неверный пароль.}
{1003}{}{|4291317840 Аккаунт с таким именем уже есть - измените логин.}
{1004}{}{|4291317840 Игрок под этим логином уже в игре.}
{1005}{}{|4291317840 Неверные данные SPECIAL.}
{1006}{}{|4291317840 Регистрация пройдена успешно.}
{1007}{}{|4291317840 Идет соединение с сервером.}
{1008}{}{|4291317840 Сбой соединения! При повторениях сбоя - обратитесь к администратору сервера.}
{1009}{}{|4291317840 Неверный логин или пароль.}
{1010}{}{|4291317840 Соединение установлено, аутентификация...}
{1012}{}{|4291317840 Гексы для высадки заняты, попробуйте войти в игру немного позже.}
{1013}{}{|4291317840 Отключение по команде игрока.}
{1014}{}{|4291317840 Ошибка в имени. Возможно слишком длинное или короткое.}
{1015}{}{|4291317840 Ошибка в одном из склонений имени. Возможно слишком длинное или короткое.}
{1016}{}{|4291317840 Пол введен неверно.}
{1017}{}{|4291317840 Возраст введен неверно.}
{1018}{}{|4291317840 Не удалось подключиться к серверу игры.}
{1019}{}{|4291317840 Введены неверные данные.}
{1020}{}{|4291317840 Ошибка поиска стартовой локации, свяжитесь с администрацией сервера.}
{1021}{}{|4291317840 Ошибка поиска стартовой карты, свяжитесь с администрацией сервера.}
{1022}{}{|4291317840 Ошибка поиска стартовых координат, свяжитесь с администрацией сервера.}
{1023}{}{|4291317840 Ошибка БД, свяжитесь с администрацией сервера.}
{1024}{}{|4291317840 Неверная версия сетевого протокола, обновите клиент.}
{1025}{}{|4291317840 Ошибка в передаче данных, попробуйте еще раз.}
{1026}{}{|4291317840 Неверное сетевое сообщение.}
{1027}{}{|4291317840 Внутренняя ошибка сервера №1, сообщите о ней администрации сервера.}
{1028}{}{|4291317840 Аутентификация пройдена, загрузка карты.}
{1029}{}{|4291317840 Выберите 3 умения.}
{1030}{}{|4291317840 Имя должно быть написано с использованием одного языка.}
{1031}{}{|4291317840 Имя на 70% должно состоять из букв алфавита.}
{1032}{}{|4291317840 Пробел не может быть использован в начале или конце имени.}
{1033}{}{|4291317840 Не допускается ставить в имени два пробела подряд.}
{1034}{}{|4291317840 Ваш аккаунт заблокирован.}
{1035}{}{|4291317840 Недопустимые символы в имени.}
{1036}{}{|4291317840 Недопустимые символы в пароле.}
{1037}{}{|4291317840 Ошибка загрузки пользовательского интерфейса.}
{1038}{}{|4291317840 Ошибка выполнения стартового скрипта.}
{1039}{}{|4291317840 Выбранный язык не поддерживается. Установлен язык по умолчанию.}
{1040}{}{|4291317840 Игра может работать некорректно при разрешениях меньше 800x600 или больше 1280x1024.}
{1041}{}{|4291317840 Тук-тук, кто-нибудь есть?}
{1042}{}{|4291317840 Обнаружены частые регистрации с одного IP адреса. Попробуйте позже.}
{1043}{}{|4291317840 Ваш IP заблокирован.}
{1044}{}{|4291317840 Минимальное время игры с одного компьютера для одного аккаунта составляет 10 минут.}
{1045}{}{|4291317840 Времени осталось: @lex time@ минут.}
{1046}{}{|4291317840 Вы были забанены.}
{1047}{}{|4291317840 Бан от: @lex banby@, Продолжительность: @lex time@ часов, Комментарий: @lex reason@.}
{1048}{}{|4291317840 Ошибка скрипта, обратитесь к администрации сервера.}
{1049}{}{|4291317840 Ваш персонаж полностью умер, игра за данный аккаунт больше невозможна.}

# Singleplayer messages
{1070}{}{|4291317840 Игра сохранена.}
{1071}{}{|4291317840 Ошибка сохранения игры.}
{1072}{}{|4291317840 Игра загружена.}
{1073}{}{|4291317840 Ошибка загрузки игры.}
{1074}{}{|4291317840 Новая игра начата.}
{1075}{}{|4291317840 Ошибка начала новой игры.}

####################################################################################################################################
#
#		Character
#
####################################################################################################################################

#
# STAT LEVEL DESCRIPTIONS
#
{2301}{}{Гадко}
{2302}{}{Плохо}
{2303}{}{Низко}
{2304}{}{Неплохо}
{2305}{}{Средне}
{2306}{}{Xорошо}
{2307}{}{Высоко}
{2308}{}{Отлично}
{2309}{}{Круто}
{2310}{}{Герой!}

#Abbreviated, for editor
{2311}{}{Гадко}
{2312}{}{Плохо}
{2313}{}{Низко}
{2314}{}{Непл.}
{2315}{}{Средн.}
{2316}{}{Xорош.}
{2317}{}{Высок.}
{2318}{}{Отлич.}
{2319}{}{Круто}
{2320}{}{Герой!}

#
#   SKILL ATTRIBUTES
#
#   Updated: 6/5/97 KSW
#   Updated to New Skill System: 9/16/98 rwh2
#
{3300}{}{+ (4 х ЛВ)}
{3301}{}{+ (2 х ЛВ)}
{3302}{}{+ (2 х ЛВ)}
{3303}{}{+ (ЛВ + СЛ)х2}
{3304}{}{+ (ЛВ + СЛ)х2}
{3305}{}{+ (4 х ЛВ)}
{3306}{}{+ (ВС + ИН)х2}
{3307}{}{+ (ВС + ИН)}
{3308}{}{+ (3 х ЛВ)}
{3309}{}{+ (ВС + ЛВ)}
{3310}{}{+ (3 х ЛВ)}
{3311}{}{+ (ВС + ЛВ)}
{3312}{}{+ (4 x ИН)}
{3313}{}{+ (3 х ИН)}
{3314}{}{+ (5 x ОБ)}
{3315}{}{+ (4 x ОБ)}
{3316}{}{+ (5 x УД)}
{3317}{}{+ (ВН + ИН)х2}
#
# SKILLDEX
#
{3340}{}{УМЕНИЯ}
{3341}{}{ОТКАЗ}

#
#   Skill Use Text
#
{3400}{}{Вы пока не воскрешаете мертвых.}
{3400}{}{Пусть мертвые почиют с миром.}
{3400}{}{Не тронь дохляков.}
{3401}{}{Подождите немного, похоже, вы исчерпали себя.}
{3401}{}{Вы слишком устали.}
{3401}{}{Такое напряжение убьет вас.}
{3402}{}{Вы не нуждаетесь в помощи санитара.}
{3403}{}{Вы не нуждаетесь в помощи доктора.}
{3404}{}{Для лечения травмы требуется навык доктора.}
{3405}{}{Для лечения этих повреждений требуется навык первой помощи.}

{3412}{}{Вы лечите раненый глаз.}
{3413}{}{Вы лечите сломанную правую руку.}
{3414}{}{Вы лечите сломанную левую руку.}
{3415}{}{Вы лечите сломанную правую ногу.}
{3416}{}{Вы лечите сломанную левую ногу.}
{3422}{}{Вы не лечите раненый глаз.}
{3423}{}{Вы не лечите сломанную правую руку.}
{3424}{}{Вы не лечите сломанную левую руку.}
{3425}{}{Вы не лечите сломанную правую ногу.}
{3426}{}{Вы не лечите сломанную левую ногу.}

{3430}{}{Вас пытались обокрасть!}
{3431}{}{Вам пытались что-то подложить!}

{3440}{}{Попытка взлома безуспешна.}
{3441}{}{Вы не смогли устновить ловушку.}
{3442}{}{Вы устанавливаете ловушку.}
{3443}{}{Вы не смогли снять ловушку.}
{3444}{}{Вы смогли разминировать ловушку.}
{3445}{}{Вы не можете войти в режим скрытности, когда вас кто-нибудь видит.}

{3450}{}{Вы прибавили %d очков жизней.}
{3451}{}{Вы и без того здоровы.}
{3452}{}{%s и без того выглядит неплохо.}
{3453}{}{Попытка лечения не удалась.}
{3455}{}{Вы получаете %d Опыта за использование умений.}
{3459}{}{\nskill_use: неправильное умение.}
{3461}{}{Вы не видите ловушек.}
{3462}{}{Вы так ничего и не узнали.}
{3463}{}{Ремонту не подлежит.}
{3470}{}{Вам не удалось похитить %s.}
{3471}{}{Вы похищаете %s.}
{3472}{}{Вы не сумели установить %s.}
{3473}{}{Вы устанавливаете %s.}
{3495}{}{Вы не так умелы, чтобы излечивать настолько тяжелые раны.}
{3496}{}{Починить этого робота невозможно.}

#
#	 PC STAT NAMES
#
{4000}{}{Очки характеристик}
{4001}{}{Следующий уровень}
{4002}{}{Осталось очков умений}
{4003}{}{Уровень}
{4004}{}{Опытность}
{4005}{}{Репутация}
{4006}{}{Карма}
{4007}{}{Бонусы}
{4008}{}{Убито}
{4009}{}{Очки умений}
{4010}{}{Способности}
{4011}{}{Дополнительно}
{4012}{}{Умения}
#
#	 PC STAT DESCRIPTIONS
#
{4050}{}{Количество очков, оставшихся для добавления к одной из базовых характеристик персонажа.}
{4051}{}{Количество очков опыта, необходимых для получения следующего уровня.}
{4052}{}{Количество очков, полученных при повышении уровня. Можно увеличить умение на 1%, или способность на 2% за потраченное очко.}
{4053}{}{Общая компетентность вашего персонажа. Изменяется в зависимости от полученного вами опыта.}
{4054}{}{Вознаграждение за выполнение определенных задач или победу в схватке с врагами. Для получения высоких уровней необходимо совершенствовать опыт.}
{4055}{}{Известная миру информация о ваших деяниях, их оценка в народе. Влияет на прием вашего героя.}
{4056}{}{Эффект от предпринятых вами действий за время игры.}
{4057}{}{Бонусы прибавляют дополнительные способности. За каждый третий уровень опыта вы получаете один бонус.}
{4058}{}{Количество существ, погибших в вашем присутствии от естественных причин, как-то автоматных очередей, взрывов гранат и огнеметных залпов.}
{4059}{}{Увеличивайте свои умения распределением очков.}
{4060}{}{Вы обязаны выбрать три способности, в которых будет специализироваться ваш персонаж. За каждую он получит бонус 20%, а повышаться они будут вдвое быстрее.}
{4061}{}{Дополнительные способности описывают вашего персонажа более подробно. Все они имеют свои положительные и отрицательные стороны. Во время создания можно выбрать максимум две.}
{4062}{}{Умения накапливаются с опытом и изучением, а, кроме того, во время разных событий по игре. Чем выше те или иные умения, тем больше вероятность ваших успешных действий.}

#
#  Experience-gain messages
#
{4090}{}{Вы получили новый уровень.}
{4091}{}{Вы получили VALUE опыта.}
{4092}{}{Вы получили %d очков опыта за убийство существа : %s.}
{4093}{}{%s вы получили %d очков опыта.}
{4094}{}{За победу над врагами, }  # 622-626 prepend to line 621
{4095}{}{За уничтожение противника, }
{4096}{}{Вы победили в этом бою, }
{4097}{}{За разгром ваших врагов }
{4098}{}{За уничтожение противника без единой царапины, }

#
# Editor
#
{4104}{}{ЛЕТ}
{4105}{}{ПОЛ}
{4106}{}{ИМЯ}
{4107}{}{МУЖ.}
{4108}{}{ЖЕН.}
{4109}{}{БОНУСЫ}
{4110}{}{КАРМА}
{4111}{}{УБИТО}
{4112}{}{ОЧКИ УМЕНИЙ}
{4113}{}{Уровень: %d}
{4114}{}{Опыт: %d}
{4115}{}{След. ур.: %d}

#
# Damage info texts
#

{4250}{}{Жизни  %d/%d}

#
# Karma
#

{6000}{}{Карма}
{6001}{}{: %d (%s)}  # Value, Desc
{6002}{}{Этот параметр отвечает за вашу репутацию. Чем он выше, тем лучше к вам будут относиться хорошие персонажи и мирные жители. С отрицательной репутацией все будут вас ненавидеть.}

{6099}{}{9} # Max values
{6100}{}{1000} # Min value
{6101}{}{Спаситель обреченных} # Desc
{6102}{}{2000} # Picture index
{6103}{}{750}
{6104}{}{Надежда пустыни}
{6105}{}{2001}
{6106}{}{500}
{6107}{}{Щит надежды}
{6108}{}{2002}
{6109}{}{250}
{6110}{}{Защитник}
{6111}{}{2003}
{6112}{}{-249}
{6113}{}{Странник}
{6114}{}{2004}
{6115}{}{-500}
{6116}{}{Нечисть}
{6117}{}{2005}
{6118}{}{-750}
{6119}{}{Омраченная душа}
{6120}{}{2006}
{6121}{}{-1000}
{6122}{}{Бич пустоши}
{6123}{}{2007}
{6124}{}{-2147483648}
{6125}{}{Дьявольское отродье}
{6126}{}{2008}

#
# Town reputation
#

{6405}{}{Репутация}
{6406}{}{Отмечает вашу репутацию среди жителей разных поселений.}

# Name
{6500}{}{Поклонение}
{6501}{}{Любовь}
{6502}{}{Симпатия}
{6503}{}{Апатия}
{6504}{}{Скука}
{6505}{}{Злоба}
{6506}{}{Ярость}

# Desc
{6550}{}{Каждый человек отсюда стремится хоть немного походить на вас. Вас носят на руках, прославляют в стихах и песнях и называют детей в вашу честь.}
{6551}{}{Когда вы здесь появляетесь, люди радостно приветствуют вас. Все они что-нибудь слышали о вас и желают вам всего самого наилучшего.}
{6552}{}{Xотя никто не бросается вас обнимать, как только увидит, местные жители хорошо к вам относятся. У них сложилось в целом приятное о вас впечатление.}
{6553}{}{Несмотря на подозрительное отношение к незнакомым людям, вы ни у кого не вызываете ни положительных, ни отрицательных эмоций.}
{6554}{}{Появившийся неизвестно откуда чужак - так думают все и ждут от вас какой-либо каверзы.}
{6555}{}{Своим поведением вы доказали, что вас подозревали не зря. Увидев вас, люди начинают перешептываться и показывать пальцем, как будто на внезапно объявившегося сборщика налогов.}
{6556}{}{С опаской поглядывая в вашу сторону, местные жители обходят вас за километр, плюют вам в спину и отворачиваются при попытке заговорить. Всем известно, что хуже и гаже вас никого нет.}

#
# Addiction title
#

{6900}{}{Привычки}
{6901}{}{Возникшие у вас вредные привычки.}


####################################################################################################################################
#
#		Items games
#
####################################################################################################################################

# Сообщение в мессаджбокс при наведении на объект
{10000}{}{Вы видите: NAME.}
# При рассмотрении объекта
{10004}{}{NAME}
# Имя или инфо не найдено
{10010}{}{Вы не видите ничего необычного.}
# Item not found in container (possible another critter take it)
{10020}{}{Предмет не найден, возможно его взял кто-то другой.}

# Container
{10100}{}{Закрыто.}
{10101}{}{Вы обыскали %s.}
{10102}{}{Вы закрыли %s.}

#
# Use text messages
#
{10200}{}{Вы применили: %s.}
{10201}{}{Вы применили: %s на %s.}
{10202}{}{Из этого ничего не вышло.}
{10203}{}{К своей досаде, вы догадались, что перед вами обычный труп.}
{10204}{}{Когда вы нагнулись и посмотрели, то обнаружили мертвое тело.}
{10205}{}{Жаль, но вы опоздали.}
{10206}{}{Это все как мертвому припарки.}
{10207}{}{Вы засветили фонарь.}
{10208}{}{Фонарь уже зажжен.}
{10209}{}{Вы установили таймер.}
{10210}{}{Таймер давно начал работу!}
{10211}{}{Вход кажется заблокирован.}
# Solar scotcher
{10240}{}{Вы не можете перезарядить батарейки - не хватает света.}
# Car
{10250}{}{Вы подзарядили машину энергией.}
{10251}{}{Энергоблок машины уже полностью заряжен.}
{10252}{}{Вы успешно отремонтировали машину.}
{10253}{}{Машина не нуждается в ремонте.}
{10254}{}{Этот двигатель не работает на данном виде топлива.}
{10255}{}{Кончилось топливо.}
{10256}{}{Машина сломана.}
{10257}{}{Машина не рассчитана на такое количество людей, уберите лишних.}
{10258}{}{Ваша харизма не позволяет руководить таким количеством людей, уберите лишних.}
{10259}{}{Нельзя отсоединять от группы находясь на воде.}
# Drugs
{10300}{}{Вы получили @lex value@ @lex name@.}
{10301}{}{Вы потеряли @lex value@ @lex name@.}
{10302}{}{Вы чувствуете облегчение.}
{10303}{}{Вы получили инфаркт от чрезмерной передозировки химикалий.}
{10304}{}{По-видимому, ничего не происходит.}
{10305}{}{%s корчится от воздействия различных химикалий.}
{10306}{}{На вас применили какой-то наркотик!}
{10307}{}{На вас пытались применить какой-то наркотик!}
# Geiger
{10350}{}{У счетчика Гейгера кончились заряды.}
{10351}{}{Счетчик Гейгера включен.}
{10352}{}{Счетчик Гейгера выключен.}
{10353}{}{Вы провели счетчик Гейгера над своим телом. На табло появились цифры: @lex rem@.}
{10354}{}{На табло появились цифры: @lex rem@.}
{10355}{}{Ничего не происходит.}
{10356}{}{Счетчик Гейгера подзаряжен.}
{10357}{}{Счетчик Гейгера заряжен на @lex cur@/@lex max@.}
# Weapon Damage
{10400}{}{Легк.}
{10401}{}{Средн.}
{10402}{}{Тяжел.}
{10403}{}{Экстрем.}
# Weapon Range
{10410}{}{Корот.}
{10411}{}{Средн.}
{10412}{}{Дальн.}
# Books
{10450}{}{Вы прочитали книгу.}
{10451}{}{Вы не узнали ничего нового.}
{10452}{}{Вы уяснили новую научную информацию.}
{10453}{}{Вы многое поняли о способах починки сломанной электроники.}
{10454}{}{Вы узнали новые способы обработки ран.}
{10455}{}{Вы научились лучше обращаться с оружием.}
{10456}{}{Вы научились лучше обращаться с энергетическим оружием.}
{10457}{}{Вы изучили новые способы выживания в пустыне.}
# Use on
{10500}{}{Запасы в Сумке Доктора подошли к концу.}
{10501}{}{Запасы в Аптечке Первой помощи подошли к концу.}
{10502}{}{Запрещено делать это во время боя.}
{10503}{}{Этот персонаж не будет торговать с вами.}
{10504}{}{Этот персонаж ничего вам не собирается говорить.}
{10505}{}{Вы не подберете этот предмет. Вы и так слишком нагружены разными вещами.}
{10506}{}{Медикаменты в Санитарной Сумке подошли к концу.}
{10507}{}{Запасы лекарств в Армейской Полевой Аптечке истощились.}
{10508}{}{Это существо не может ничего нести.}
# Grave
{10550}{}{Эта могила разрыта.}
{10551}{}{Эта могила зарыта.}

####################################################################################################################################
#
#		Calibers (from PROTO.MSG)
#
####################################################################################################################################

#
# Caliber Types for weapons
#
{10900}{}{Нету}
{10901}{}{Ракета}
{10902}{}{Топливо огнемета}
{10903}{}{Энергопак С}
{10904}{}{Энергопак Д}
{10905}{}{.223}
{10906}{}{5мм}
{10907}{}{.40 кал.}
{10908}{}{10мм}
{10909}{}{.44 кал.}
{10910}{}{14мм}
{10911}{}{Дробь}
{10912}{}{9мм}
{10913}{}{ББ}
{10914}{}{.45 кал.}
{10915}{}{2мм}
{10916}{}{Обойма 4.7мм}
{10917}{}{Основные XН}
{10918}{}{7.62мм}
{10919}{}{.700 Найтро Экспресс}
{10920}{}{Сигнальная ракета}
####################################################################################################################################
#
#		Critters game
#
####################################################################################################################################

#
#	Male
#

##First words
#For age and conditions
{11000}{}{Вы видите }
{11001}{}{Это вы }
#For special
{11002}{}{На вид }
#For damages
{11003}{}{У него }

#Self look
{11005}{}{Опа, это же ты.}
{11005}{}{Какие люди в голливуде.}
{11005}{}{Кто же это?}
{11005}{}{Чувак, ты им можешь управлять.}
{11005}{}{Перестань меня разглядывать!!!}

#Default view
{11010}{}{Вы видите: NAME.}
{11011}{}{Вы видите лежачего: NAME.}
{11012}{}{Вы видите труп: NAME.}
{11013}{}{Вы видите останки: NAME.}
{11014}{}{Вы не видите ничего необычного.}

##Age, max age 99
#<=16
{11116}{}{пацана}
#<=30
{11130}{}{молодого человека}
#<=40
{11140}{}{мужчину средних лет}
#<=60
{11160}{}{пожилого мужчину}
#>60
{11199}{}{старика}

##Conditions
#Prepare to fight
{11212}{}{его тело странно напряжено, он готов атаковать в любую секунду}
#Knock out face up
{11221}{}{он лежит на земле, явно не загорает}
#Knock out face down
{11222}{}{он решил поспать}
#Dead normal face up
{11231}{}{он немного мертв}
#Dead normal face down
{11232}{}{по ходу, мертв}

##Special
#S
{11301}{}{хилый}
{11302}{}{хлипкий}
{11303}{}{слабый}
{11308}{}{силен}
{11309}{}{очень силен}
{11310}{}{очень силен}
#P
#E
{11321}{}{хрупкого телосложения}
{11322}{}{хрупкого телосложения}
{11325}{}{среднего телосложения}
{11326}{}{среднего телосложения}
#C
{11331}{}{невзрачный}
{11332}{}{невзрачный}
{11333}{}{невзрачный}
{11337}{}{привлекательный}
{11338}{}{обворожительный}
{11339}{}{общительный}
{11340}{}{очень обаятельный}
#I
{11341}{}{тупорылый}
{11342}{}{тупоумный}
{11343}{}{слабоумный}
{11347}{}{интеллектуал}
{11348}{}{интеллектуал}
{11349}{}{гений}
{11350}{}{гениальная личность}
#A
{11351}{}{неуклюжий}
{11352}{}{неуклюжий}
{11357}{}{спортсмен}
{11358}{}{акробат}
{11359}{}{очень ловкий}
{11360}{}{очень ловкий}
#L
{11361}{}{несчастный}
{11362}{}{несчастливый}
{11363}{}{несчастливый}
{11368}{}{веселый}
{11369}{}{энтузиаст}
{11370}{}{очень удачливый}

##Damages
#Poisoned
{11400}{}{странные волдыри на коже}
#Radiated
{11401}{}{тело непонятно светиться}
#Eyes
{11402}{}{повреждены глаза}
#Right Arm
{11403}{}{вся правая рука в крови}
#Left Arm
{11404}{}{из левой руки хлещет кровь}
#Right Leg
{11405}{}{похоже сломана правая нога}
#Left Leg
{11406}{}{левая нога сильно повреждена}

#
#	Female
#

##First words
#For age and conditions
{12000}{}{Вы видите }
{12001}{}{Это вы }
#For special
{12002}{}{На вид }
#For damages
{12003}{}{У нее }

#Self look
{12005}{}{Епт, этож ты.}
{12005}{}{Какие люди в голливуде.}
{12005}{}{Кто же это?}
{12005}{}{Перестань меня разглядывать!!!}
{12005}{}{А я секси. Да?}

##Age, max age 99
#<=16
{12116}{}{девочку}
#<=30
{12130}{}{девушку}
#<=40
{12140}{}{женщину средних лет}
#<=60
{12160}{}{пожилую женщину}
#>60
{12199}{}{старуху}

##Conditions
#Prepare to fight
{12212}{}{ее тело странно напряжено, она готова атаковать в любую секунду}
#Knock out face up
{12221}{}{она лежит на земле, явно не загорает}
#Knock out face down
{12222}{}{она решила поспать}
#Dead normal face up
{12231}{}{она немного мертва}
#Dead normal face down
{12232}{}{по ходу, мертва}

##Special
#S
{12301}{}{хилая}
{12302}{}{хлипкая}
{12303}{}{слабая}
{12308}{}{сильная}
{12309}{}{очень сильна}
{12310}{}{очень сильна}
#P
#E
{12321}{}{хрупкого телосложения}
{12322}{}{хрупкого телосложения}
{12325}{}{среднего телосложения}
{12326}{}{среднего телосложения}
#C
{12331}{}{невзрачная}
{12332}{}{невзрачная}
{12333}{}{невзрачная}
{12337}{}{привлекательная}
{12338}{}{обворожительная}
{12339}{}{общительная}
{12340}{}{очень обаятельная}
#I
{12341}{}{тупорылая}
{12342}{}{тугоумная}
{12343}{}{слабоумная}
{12347}{}{интеллектуал}
{12348}{}{интеллектуал}
{12349}{}{гений}
{12350}{}{гениальная личность}
#A
{12351}{}{неуклюжая}
{12352}{}{неуклюжая}
{12357}{}{спортсменка}
{12358}{}{акробатка}
{12359}{}{очень ловкая}
{12360}{}{очень ловкая}
#L
{12361}{}{несчастная}
{12362}{}{несчастливая}
{12363}{}{несчастливая}
{12368}{}{веселая}
{12369}{}{энтузиастка}
{12370}{}{очень удачливая}

##Damages
#Poisoned
{12400}{}{странные волдыри на коже}
#Radiated
{12401}{}{тело непонятно светиться}
#Eyes
{12402}{}{повреждены глаза}
#Right Arm
{12403}{}{вся правая рука в крови}
#Left Arm
{12404}{}{из левой руки хлещет кровь}
#Right Leg
{12405}{}{похоже сломана правая нога}
#Left Leg
{12406}{}{левая нога сильно повреждена}

#
# Without awareness: 0 + 1 + [2]
# With awareness: 3 + [2] + [4]
#
{12500}{}{Объект }   # Male
{12501}{}{Объект }   # Female
{12502}{}{Объект }   # It
{12510}{}{мертв}               # Dead condition
{12511}{}{почти мертв}         # <34% hp
{12512}{}{тяжело ранен}        # <67% hp
{12513}{}{ранен}               # <100% hp
{12514}{}{целехонек}           # 100% hp
{12520}{}{есть поврежденные органы}      # Male hurt
{12521}{}{, но есть поврежденные органы} # Male unhurt
{12522}{}{есть поврежденные органы}      # Female hurt
{12523}{}{, но есть поврежденные органы} # Female unhurt
{12524}{}{есть поврежденные органы}      # It hurt
{12525}{}{, но есть поврежденные органы} # It unhurt
{12530}{}{У него есть CUR/MAX жизней} # Male
{12531}{}{У нее есть CUR/MAX жизней}  # Female
{12532}{}{Оно имеет CUR/MAX жизней}   # It
{12540}{}{ и носит при себе WEAPON}                        # Gun without holder
{12541}{}{ и носит при себе WEAPON с CUR/MAX зарядов AMMO} # Gun with holder
{12542}{}{ и носит при себе MISC}                          # Any other item

#
# Other
#

{12600}{}{Ваш криттер не может передвигаться.}

####################################################################################################################################
#
#		Plagues
#
####################################################################################################################################

{12800}{}{Вы чувствуете тошноту.}
{12801}{}{Вы чувствуете тошноту, и после нескольких приступов рвоты сильно утомляетесь.}
{12802}{}{Вы сильно устали, но приступы рвоты не прекращаются, и вы еще долго не можете прийти в себя.}
{12803}{}{У вас кровь идет горлом, выпадают волосы и облезает кожа на открытых участках тела. }
{12804}{}{У вас кровь идет горлом, выпадают волосы и со всего тела отваливается кожа. Рвота не прекращается. Вам не стоило увлекаться работой под Вин95.}
{12805}{}{Все внутренние органы кровоточат, у вас сильный понос и непрекращающаяся рвота. Вы корчитесь от боли и призываете смерть.}
{12806}{}{Вы скончались от лучевой болезни.}
{12807}{}{Вы получили большую дозу радиации.}
{12808}{}{Счетчик Гейгера отметил наличие радиации.}
{12809}{}{Счетчик Гейгера как будто взбесился.}
{12810}{}{Вы ощущаете действие яда!}
{12811}{}{Вы страдаете от отравления.}
{12812}{}{Вы чувствуете себя немного лучше.}
{12813}{}{Вам сильно полегчало.}

####################################################################################################################################
#
#		Scores
#
####################################################################################################################################

{13000}{}{Герои на час}
{13001}{}{Злодей на час (минимальная  значение кармы)}
{13011}{}{Герой на час (максимальное значение кармы)}
{13021}{}{Событие часа (максимальное изменение кармы за последний час)}

{13030}{}{Передовики}
{13031}{}{Почетный оратор (cамый говорливый)}
{13041}{}{Почетный торговец (cамый оборотистый)}
{13051}{}{Почетный зомби (cамый убиваемый)}
{13061}{}{Почетный обаяшка (cамый ветренный)}
{13071}{}{Почетный маньяк (cамый неадекватный)}
{13081}{}{Почетный скаут (cамый мобильный)}
{13091}{}{Почетный Айболит (cамый человеколюбивый)}
{13101}{}{Почетный стрелок (cамый огнестрельный)}
{13111}{}{Почетный клинок (cамый колюще-режущий)}
{13121}{}{Почетный кулак (cамый драчливый)}
{13131}{}{Почетный вор (cамый вороватый)}

{13140}{}{Профессионалы}
{13141}{}{Перевозчик (больше всего людей перевезено)}
{13151}{}{Убийца (больше всего существ убито)}
{13161}{}{Снайпер (больше всего критических попаданий)}
{13171}{}{Искатель приключений (больше всего квестов пройдено)}
{13181}{}{Взломщик (больше всего удачных взломов)}
{13191}{}{Костолом (больше всего рукопашных повреждений)}
{13201}{}{Нувориш (больше всего денег)}

{13210}{}{Избранный}
{13211}{}{Избранный (cамый cамый)}

{13400}{}{Базы}
{13401}{}{Текущий хозяин базы Сиерра}
{13411}{}{Текущий хозяин базы Марипоза}
{13421}{}{Текущий хозяин Собора}
{13431}{}{Лучший хозяин базы Сиерра}
{13441}{}{Лучший хозяин базы Марипоза}
{13451}{}{Лучший хозяин Собора}
{13461}{}{Принадлежность базы Сиерра}
{13471}{}{Принадлежность базы Марипоза}
{13481}{}{Принадлежность Собора}
{13491}{}{Большее предпочтение отдано организации}

####################################################################################################################################
#
#		Stats (with STAT.MSG + 2000)
#
####################################################################################################################################


# ST_STRENGTH
{100001}{}{Сила}
{100002}{}{Грубая физическая сила. Хорошо подходит для воинов и им подобных. Оказывает влияние на Очки Жизней, наносимые Повреждения и Переноску Груза.}

# ST_PERCEPTION
{100011}{}{Восприятие}
{100012}{}{Способность иначе видеть, слышать, замечать и предчувствовать события. Необходимое качество для каждого снайпера. Оказывает влияние на Дальность стрельбы и Порядок действий.}
# ST_ENDURANCE
{100021}{}{Выносливость}
{100022}{}{Выносливость помогает переносить тяготы и лишения судьбы героя с подобающим спокойствием. Оказывает влияние на Очки Жизней, Устойчивость к Яду и Радиации, Уровень Лечения и др.}
# ST_CHARISMA
{100031}{}{Обаяние}
{100032}{}{Обаяние представляет собой комбинацию внешности и шарма. Высокое обаяние необходимо для тех персонажей, которые думают всего добиться словами. Влияет на реакцию людей и цены товаров.}
# ST_INTELLECT
{100041}{}{Интеллект}
{100042}{}{Интеллект отвечает за память, скорость реакции и способность оценивать события. Высокий Интеллект важен для всех. Влияет на количество новых умений-на-уровень, режимы диалога и многие способности.}
# ST_AGILITY
{100051}{}{Ловкость}
{100052}{}{Ловкость и координация движений не раз спасут вас от верной гибели. Каждый активный герой нуждается в ловкости. Влияет на Очки движения, Класс брони, Порядок действий и пр.}
# ST_LUCK
{100061}{}{Удача}
{100062}{}{Степень воздействия теории вероятностей на вашу судьбу. Высокая или низкая удачливость часто определяют, как вам повезет в игре, как будут развиваться дальнейшие события.}
# ST_MAX_LIFE
{100071}{}{Максимум очков жизней}
{100072}{}{Определяет, какое количество повреждений сможет вынести персонаж, прежде чем умрет. Если Очки Жизни составляют от 0 до –20, персонаж падает на землю и не может двигаться (персонаж не умирает, а начинает восстанавливать запас здоровья, как если бы он отдыхал), но отравленный персонаж умирает даже с 0 Очков Жизни.}
# ST_ACTION_POINTS
{100081}{}{Максимум очков действия}
{100082}{}{Лимит возможных действий, предпринимаемых персонажем. В режиме реального времени Очки Действия восстанавливаются за 7 секунд, в пошаговом они восстанавливаются в начале каждого хода.}
{100083}{}{Очки действий}
# ST_ARMOR_CLASS
{100091}{}{Класс брони}
{100092}{}{Влияет на вероятность поранить данного конкретного персонажа.}
{100093}{}{Класс брони}
# ST_MELEE_DAMAGE
{100101}{}{Рукопашные повреждения}
{100102}{}{Количество повреждений, причиняемых вашим персонажем в рукопашном бою.}
{100103}{}{Рукоп. повр.}
# ST_CARRY_WEIGHT
{100111}{}{Переносимый груз}
{100112}{}{Максимальный вес поклажи, который может переносить ваш персонаж, в фунтах (373 гр. по Тр.)}
{100113}{}{Макс. груз}
# ST_SEQUENCE
{100121}{}{Порядок}
{100122}{}{Определяет порядок начала активных действий вашего персонажа.}
{100123}{}{Порядок}
# ST_HEALING_RATE
{100131}{}{Уровень лечения}
{100132}{}{В конце дня, ваш персонаж будет добавлять по 1 жизни для каждого очка Уровня лечения. Во время отдыха вы лечитесь каждые шесть часов.}
{100133}{}{Уров. лечен.}
# ST_CRITICAL_CHANCE
{100141}{}{Шанс критического удара}
{100142}{}{Вероятность нанесения критических повреждений противнику определяется этим значением.}
{100143}{}{Шанс на крит.}
# ST_MAX_CRITICAL
{100151}{}{Лучшие крит. удары}
{100152}{}{Лучшие крит. удары}
# ST_NORMAL_ABSORB
{100161}{}{Количество повреждений}
{100162}{}{Количество повреждений}
# ST_LASER_ABSORB
{100171}{}{Количество повреждений Лазер}
{100172}{}{Количество повреждений Лазер}
# ST_FIRE_ABSORB
{100181}{}{Количество повреждений Огонь}
{100182}{}{Количество повреждений Огонь}
# ST_PLASMA_ABSORB
{100191}{}{Количество повреждений Плазма}
{100192}{}{Количество повреждений Плазма}
# ST_ELECTRO_ABSORB
{100201}{}{Количество повреждений Электр.}
{100202}{}{Количество повреждений Электр.}
# ST_EMP_ABSORB
{100211}{}{Количество повреждений ЭМИ}
{100212}{}{Количество повреждений ЭМИ}
# ST_EXPLODE_ABSORB
{100221}{}{Количество повреждений Взрыв}
{100222}{}{Количество повреждений Взрыв}
# ST_NORMAL_RESIST
{100231}{}{Устойчивость к повреждениям}
{100232}{}{Все получаемые повреждения уменьшаются в соответствии с данным значением. На него сильно влияет Класс брони.}
{100233}{}{Уст. к повр.}
# ST_LASER_RESIST
{100241}{}{Устойчивость к поврежд. Лазер}
{100242}{}{Устойчивость к поврежд. Лазер}
# ST_FIRE_RESIST
{100251}{}{Устойчивость к поврежд. Огонь}
{100252}{}{Устойчивость к поврежд. Огонь}
# ST_PLASMA_RESIST
{100261}{}{Устойчивость к поврежд. Плазма}
{100262}{}{Устойчивость к поврежд. Плазма}
# ST_ELECTRO_RESIST
{100271}{}{Устойчивость к поврежд. Электр.}
{100272}{}{Устойчивость к поврежд. Электр.}
# ST_EMP_RESIST
{100281}{}{Устойчивость к поврежд. ЭМИ}
{100282}{}{Устойчивость к поврежд. ЭМИ}
# ST_EXPLODE_RESIST
{100291}{}{Устойчивость к поврежд. Взрыв}
{100292}{}{Устойчивость к поврежд. Взрыв}
# ST_RADIATION_RESISTANCE
{100301}{}{Устойчивость к радиации}
{100302}{}{Количество радиационного облучения, которому вы подвергаетесь, зависит от этого значения. На него влияет тип одетой вами брони и прием антирадиационных химикатов.}
{100303}{}{Уст. к рад.}
# ST_POISON_RESISTANCE
{100311}{}{Устойчивость к яду}
{100312}{}{Уменьшает повреждения от отравления.}
{100313}{}{Уст. к яду}

# 100700
# ST_AGE
{100701}{}{Возраст}
{100702}{}{Возраст}
# ST_GENDER
{100711}{}{Пол}
{100712}{}{Пол}
# ST_CURRENT_HP
{100721}{}{Текущие очки жизней}
{100722}{}{Текущие очки Жизней}
# ST_POISONING_LEVEL
{100731}{}{Текущий уровень яда}
{100732}{}{Текущий уровень Яда}
{100733}{}{Тек. ур. яда}
# ST_RADIATION_LEVEL
{100741}{}{Текущий уровень радиации}
{100742}{}{Текущий уровень Радиации}
{100743}{}{Тек. ур. рад.}

# 100760
# ST_EXPERIENCE
{100761}{}{Опыт}
{100762}{}{Вознаграждение за выполнение определенных задач или победу в схватке с врагами. Для получения высоких уровней необходимо совершенствовать опыт.}
# ST_LEVEL
{100771}{}{Уровень}
{100772}{}{Общая компетентность вашего персонажа. Изменяется в зависимости от полученного вами опыта.}
# ST_UNSPENT_SKILL_POINTS
{100781}{}{Осталось очков умений}
{100782}{}{Количество очков, полученных при повышении уровня. Можно увеличить умение на 1%, или способность на 2% за потраченное очко.}

# 100800
# ST_KARMA
{100801}{}{Карма}
{100802}{}{Этот параметр отвечает за вашу репутацию. Чем он выше, тем лучше к вам будут относиться хорошие персонажи и мирные жители. С отрицательной репутацией все будут вас ненавидеть.}

# 112, ST_BASE_CRTYPE
{101121}{}{Тип тела}

# 150..165, 3d layers
{101501}{}{Кожа}
{101511}{}{Правая рука}
{101521}{}{Левая рука}
{101531}{}{Тело}
{101541}{}{Ноги}
{101551}{}{Руки}
{101561}{}{Голова}
{101571}{}{Волосы}
{101581}{}{Глаза}
{101591}{}{Усы}
{101601}{}{Коса}
{101611}{}{Борода}
{101621}{}{Наплечники}
{101631}{}{Браслет}
{101641}{}{Спина}
{101651}{}{Рюкзак}

####################################################################################################################################
#
#		Skills (with SKILL.MSG + 3000)
#
####################################################################################################################################

# 102000
# SK_SMALL_GUNS
{102001}{}{Легкое оружие}
{102002}{}{Использование, починка и общие знания по стрелковому оружию. Пистолетам, автоматам и винтовкам.}
# SK_BIG_GUNS
{102011}{}{Тяжелое оружие}
{102012}{}{Умение работать с тяжелым вооружением. Ручные и многоствольные пулеметы, гранатометы, огнеметы и тому подобное.}
# SK_ENERGY_WEAPONS
{102021}{}{Энергооружие}
{102022}{}{Способность эффективно применять энерго-оружие. Как вести огонь из различной лазерной и плазменной техники.}
# SK_UNARMED
{102031}{}{Рукопашная}
{102032}{}{Сочетание боевых искусств, знание рукопашного боя и навыков самообороны позволяют вам драться используя только руки и ноги.}
# SK_MELEE_WEAPONS
{102041}{}{Xолодное оружие}
{102042}{}{Использование разных подручных средств в ближнем бою. Ножи, дубинки, копья, вилы, кувалды, ломы и тому подобный хлам.}
# SK_THROWING
{102051}{}{Метательное оружие}
{102052}{}{Способность успешно применять метательные средства. Копья, гранаты и прочее в том же роде.}
# SK_FIRST_AID
{102061}{}{Санитар}
{102062}{}{Общие познания в области первой медицинской помощи. Способность лечиться от мелких порезов, царапин и прочего. По игре способность восстанавливает больше жизней, чем просто отдых.}
{102063}{}{Санитар}
# SK_DOCTOR
{102071}{}{Доктор}
{102072}{}{Излечение тяжелых ранений и умение обращаться с поврежденными частями тела. Без этой способности для излечения будет требоваться очень много времени.}
{102073}{}{Доктор}
# SK_SNEAK
{102081}{}{Скрытность}
{102082}{}{Тихое передвижение и способность оставаться незамеченным. В случае успеха вас будет гораздо тяжелее обнаружить. Вы не можете одновременно бежать и красться.}
{102083}{}{Красться}
# SK_LOCKPICK
{102091}{}{Взлом замков}
{102092}{}{Умение открывать двери, даже не имея подходящего ключа. Использование отмычек или электронных устройств сильно улучшает жизненные перспективы.}
{102093}{}{Взлом}
# SK_STEAL
{102101}{}{Воровство}
{102102}{}{Часто вы оказываетесь в состоянии позаимствовать чужие вещи без ведома владельца. Неплохо для воровской карьеры.}
{102103}{}{Кража}
# SK_TRAPS
{102111}{}{Ловушки}
{102112}{}{Способность обнаруживать и обезвреживать ловушки. Кроме того, установка зарядов взрывчатого вещества.}
{102113}{}{Ловушки}
# SK_SCIENCE
{102121}{}{Наука}
{102122}{}{Большое количество научного знания, включая работу с компьютером, биологию, физику и геологию.}
{102123}{}{Наука}
# SK_REPAIR
{102131}{}{Ремонт}
{102132}{}{Практическое применение научных знаний. Ремонт и создание снаряжения, разнообразных механизмов, электроники и оружия.}
{102133}{}{Ремонт}
# SK_SPEECH
{102141}{}{Красноречие}
{102142}{}{Способность общаться с людьми и использовать принципы риторики на практике. Убежденность в своей правоте, передающаяся собеседникам. Интуиция, позволяющая отличать ложь от правды.}
# SK_BARTER
{102151}{}{Торговля}
{102152}{}{Наука торговать и заниматься подобными вещами. Получение высоких цен за бросовый товар и покупка по дешевке хороших вещей помогут в жизни.}
# SK_GAMBLING
{102161}{}{Азартные игры}
{102162}{}{Знание и применение на практике всего, касающегося азартных игр. Вы всегда выигрываете в карты и в кости.}
# SK_OUTDOORSMAN
{102171}{}{Скиталец}
{102172}{}{Вы не остаетесь подолгу в закрытом помещении, а всегда в дороге. Вы многое знаете о зверях, птицах, растениях и пустыне.}

# 102300
# TO_SK_FIRST_AID, timeouts
{102301}{}{Первая помощь}
# TO_SK_DOCTOR, timeouts
{102311}{}{Доктор}
# TO_SK_REPAIR, timeouts
{102321}{}{Ремонт}
# TO_SK_SCIENCE, timeouts
{102331}{}{Наука}
# TO_SK_LOCKPICK, timeouts
{102341}{}{Взлом}
# TO_SK_STEAL, timeouts
{102351}{}{Кража}

# 102380
# TO_BATTLE, timeouts
{102381}{}{Боевой}
# TO_TRANSFER, timeouts
#{102391}{}{Переходы}
# TO_REMOVE_FROM_GAME, timeouts
{102401}{}{Выход из игры}
# TO_REPLICATION, timeouts
{102411}{}{Репликация}
# TO_KARMA_VOTING, timeouts
{102421}{}{Голосование}
# TO_SNEAK, timeouts
{102431}{}{Скрытность}

####################################################################################################################################
#
#		Kills (from PROTO.MSG)
#
####################################################################################################################################

#
# Kill Types names
#

# 102600
# BT_MEN..BT_BIG_BAD_BOSS, bodytypes
{102601}{}{Мужчины}
{102602}{}{Здесь указано число убитых вами за время путешествий и приключений человеческих особей мужского пола.}
{102611}{}{Женщины}
{102612}{}{Здесь указано число убитых вами за время путешествий и приключений человеческих особей женского пола.}
{102621}{}{Детишки}
{102622}{}{Здесь указано число убитых вами за время путешествий и приключений бедных маленьких человеческих детишек.}
{102631}{}{Супер Мутанты}
{102632}{}{Здесь указано число уничтоженных вами за время путешествий и приключений Супер Мутантов.}
{102641}{}{Призраки}
{102642}{}{Здесь указано число уничтоженных вами за время путешествий и приключений призраков всех видов.}
{102651}{}{Брамины}
{102652}{}{Здесь указано число порезанных вами за время путешествий и приключений браминов - мутировавших коров.}
{102661}{}{Радскорпионы}
{102662}{}{Здесь указано число уничтоженных вами за время путешествий и приключений радскорпионов.}
{102671}{}{Крысы}
{102672}{}{Здесь указано число уничтоженных вами за время путешествий и приключений крыс и им подобных.}
{102681}{}{Летатели}
{102682}{}{Здесь указано число уничтоженных вами за время путешествий и приключений летателей.}
{102691}{}{Псевдо-кентавры}
{102692}{}{Количество убитых вами псевдо-кентавров.}
{102701}{}{Роботы}
{102702}{}{Общее количество разобранных или сломанных вами в путешествиях роботов.}
{102711}{}{Собаки}
{102712}{}{Общее количество собак, отправленных вами в великую небесную конуру на веки вечные.}
{102721}{}{Мантиссы}
{102722}{}{Здесь указано число передавленных вами за время путешествий и приключений мантиссов, других насекомых и подобных им существ.}
{102731}{}{Когти смерти}
{102732}{}{Здесь указано число убитых вами Когтей Смерти и их сородичей.}
{102741}{}{Растения}
{102742}{}{Количество растений, безжалостно выполотых вашей рукой.}
{102751}{}{Ящеры}
{102752}{}{Поголовье ящеров, истребленных вами во время путешествий по стране.}
{102761}{}{Чужие}
{102762}{}{Число инопланетных существ, погибших от вашей руки.}
{102771}{}{Муравьи}
{102772}{}{Количество мутировавших насекомых - бывших муравьев, уничтоженных вами в пустыне.}
{102781}{}{Большие боссы}
{102782}{}{Подсчет бесноватых маньяков убийства, генетически созданных киборгов - Суперагентов, павших в бою с вами.}
{102791}{}{Гигантские жуки}
{102792}{}{Количество мутировавших жуков, уничтоженных вами в Пустоши.}
{102801}{}{Гигантские осы}
{102802}{}{Количество мутировавших гигантских ос, погибших от вашей руки.}


####################################################################################################################################
#
#		Perks (with PERK.MSG)
#
####################################################################################################################################

# 103000
# PE_BOOKWORM
{103001}{}{Книголюб}
{103002}{}{Книголюб.}
# PE_AWARENESS
{103011}{}{Осведомленность}
{103012}{}{Вы постоянно держитесь себе на уме и замечаете больше деталей об окружающих вас людях. При осмотре вы получаете исчерпывающую информацию.}
# PE_BONUS_HTH_ATTACKS
{103021}{}{Доп. рукопашн. атаки}
{103022}{}{Вы знакомы с тайными боевыми искусствами востока, или попросту чаще бьете. Как бы там ни было, ваши рукопашные атаки занимают на 1 ОД меньше.}
# PE_BONUS_HTH_DAMAGE
{103031}{}{Доп. рукопашн. повр.}
{103032}{}{Большой опыт рукопашных схваток научили вас уделять внимание, прежде всего наносимому повреждению. При ударе рукой или холодным оружием враг теряет на 2 очка жизней больше.}
# PE_BONUS_MOVE
{103041}{}{Бонус движения}
{103042}{}{За каждый уровень данного бонуса вы получаете 2 ОД, которые используются только для перемещения. Иными словами, с каждым уровнем бонуса вы получаете 2 дополнительных шага.}
# PE_BONUS_RANGED_DAMAGE
{103051}{}{Бонус точности}
{103052}{}{Ваши тренировки в обращении со стрелковым оружием сделали свое дело. На каждый уровень данного бонуса наносимые вами при стрельбе повреждения увеличиваются на 2.}
# PE_BONUS_RATE_OF_FIRE
{103061}{}{Бонус скорости}
{103062}{}{Теперь вы нажимаете на курок немного быстрее, но остаетесь по-прежнему точны. Время, расходуемое на атаку, уменьшается на 1 Очко Движения.}
# PE_EARLIER_SEQUENCE
{103071}{}{Быстрая реакция}
{103072}{}{Враги всегда будут ошибаться, ведь прав тот, кто выстрелил первым, а ваш порядок действий увеличивается на 2 с каждым уровнем.}
# PE_FASTER_HEALING
{103081}{}{Быстрое лечение}
{103082}{}{С каждым уровнем данного бонуса вы начинаете лечиться на два очка быстрее, а это верный залог успеха в пустыне.}
# PE_MORE_CRITICALS
{103091}{}{Больше крит. атак}
{103092}{}{Если у вас есть этот бонус, вероятность нанесения критических повреждений противнику увеличивается на 5 процентов. Очень неплохо для снайперов, один выстрел - один труп.}
# PE_NIGHT_VISION
{103101}{}{Ночное зрение}
{103102}{}{Ваши глаза стали привычными к темноте, а зрачки улавливают самый тусклый отблеск света. С каждым уровнем вы видите лучше на 20 процентов.}
# PE_PRESENCE
{103111}{}{Важный вид}
{103112}{}{Входя в комнату, вы сразу привлекаете к себе внимание. Начальная реакция другого человека по отношению к вам улучшается на 10 процентов на уровень бонуса.}
# PE_RAD_RESISTANCE
{103121}{}{Уст. к радиации}
{103122}{}{Вы лучше переносите пагубное воздействие радиации на организм. Каждый уровень бонуса добавляет 15 процентов к вашей Устойчивости к Радиации.}
# PE_TOUGHNESS
{103131}{}{Крутизна}
{103132}{}{Крутизна позволяет вам не замечать мелкие жизненный неприятности. Вы получаете 10 процентов устойчивости к повреждениям.}
# PE_STRONG_BACK
{103141}{}{Переноска}
{103142}{}{Способность таскать тяжелые грузы - далеко не лишняя в условиях пустыни. Прибавка 50 фунтов груза.}
# PE_SHARPSHOOTER
{103151}{}{Меткость}
{103152}{}{Искусство попадать в цель на большом расстоянии. При определении дистанции вы получаете бонус 2 к восприятию на каждом уровне. Пристрелите своего противника, когда он ни о чем не догадывается!}
# PE_SILENT_RUNNING
{103161}{}{Бесшумный бег}
{103162}{}{Теперь вы будете быстро двигаться, при этом, создавая не больше шума, чем если бы вы крались на цыпочках. Ранее это было совершенно неосуществимо в силу технических причин.}
# PE_SURVIVALIST
{103171}{}{Живучесть}
{103172}{}{Привычка к долгой жизни в пустыне выработала у вас невероятную живучесть. В соответствующих обстоятельствах вы как Скиталец получаете 25 процентов бонуса.}
# PE_MASTER_TRADER
{103181}{}{Торговля}
{103182}{}{Вы добились настоящего мастерства в одном из аспектов торговли, а именно способности покупать товары по низким ценам, торгуясь до изнеможения. Вы получаете 25 процентов скидки на любую покупку.}
# PE_EDUCATED
{103191}{}{Образование}
{103192}{}{Каждый уровень образования будет прибавлять вам 2 очка при получении нового уровня опытности. Данный бонус будет вам полезен на ранней стадии игры.}
# PE_HEALER
{103201}{}{Лечение}
{103202}{}{Излечение страждущих легче дается вам с этим бонусом. На каждом уровне вы будете получать 4-10 добавочных очков жизни в применении способности Доктор или Первая Помощь.}
# PE_FORTUNE_FINDER
{103211}{}{Везучесть}
{103212}{}{У вас есть талант обнаруживать деньги в самых неожиданных местах, даже во время случайных стычек в пустыне.}
# PE_BETTER_CRITICALS
{103221}{}{Лучшие крит. атаки}
{103222}{}{Причиняемые вашему противнику критические удары более смертоносны. Вы получаете 20 процентный бонус для возможных повреждений, хотя вероятность нанесения такового не увеличивается.}
# PE_EMPATHY
{103231}{}{Эмпатия}
{103232}{}{Вы хорошо изучили других человеческих существ и знаете их реакцию на ваши реплики. При разговоре вы чувствуете эмоциональную реакцию собеседника и видите уровень его настроения при общении с вами.}
# PE_SLAYER
{103241}{}{Дробила}
{103242}{}{Дробящие удары ваших кулаков и ног всегда будут причинять противнику критические повреждения, сеять разрушения и хаос на своем пути.}
# PE_SNIPER
{103251}{}{Снайпер}
{103252}{}{Вы в совершенстве научились владеть стрелковым оружием. С данным бонусом при надлежащей проверке вашей Удачи каждое точное попадание будет считаться критическим для вашего противника.}
# PE_SILENT_DEATH
{103261}{}{Тихая смерть}
{103262}{}{Если вы подкрадетесь к противнику и рукой или ногой ударите его в спину, то нанесете ему двойные повреждения. Таков этот странный бонус.}
# PE_ACTION_BOY
{103271}{}{Человек действия}
{103272}{}{Человек действия все операции совершает бегом, наподобие новобранца. Это придает ему дополнительные очки действия, которые можно использовать в любых целях.}
# PE_MENTAL_BLOCK
{103281}{}{Послушник Аббатства}
{103282}{}{Вы - послушник Аббатства. Приняв это звание, вы навсегда отказываетесь от материальных благ и соглашаетесь провести всю жизнь в смирении.}
# PE_LIFEGIVER
{103291}{}{Сила жизни}
{103292}{}{С каждым уровнем данного бонуса вы получите дополнительные 4 очка Жизни. Xоть это и немного, всякое случается, а вдруг пригодится.}
# PE_DODGER
{103301}{}{Увертливость}
{103302}{}{Во время боя в вас будет гораздо сложнее попасть. Независимо от одетых на вас в этот момент доспехов, вы получаете бонус в плюс 5 очков к классу брони.}
# PE_SNAKEATER
{103311}{}{Змееглот}
{103312}{}{Любые отравляющие вещества действуют на вас крайне ослаблено. Ваша устойчивость к яду повышается на 25 процентов.}
# PE_MR_FIXIT
{103321}{}{Зубрежка}
{103322}{}{Данный бонус дает вам единовременное увеличение на 10 процентов к способностям науки и починки. Немного знаний еще никому никогда не повредили.}
# PE_MEDIC
{103331}{}{Медицина}
{103332}{}{Знание Медицины дает вам единовременный 10 процентный бонус к способностям Доктор и Первая помощь. Лечение не помешает.}
# PE_MASTER_THIEF
{103341}{}{Вор-профессионал}
{103342}{}{Этот навык увеличивает умения "Взлом" и "Воровство" на 20%. Вы становитесь настоящим Робин Гудом. Забираете у богатых и оставляете себе.}
# PE_SPEAKER
{103351}{}{Болтливость}
{103352}{}{Болтливость означает получение вами единовременного 20 процентного бонуса к способности Разговаривать с другими.}
# PE_HEAVE_HO
{103361}{}{Метание}
{103362}{}{Каждый уровень бонуса по Метанию прибавляет вам дополнительных 2 очка по Силе (вплоть до 10) к определению дальности при броске.}
# PE_FRIENDLY_FOE
{103371}{}{Дружественный противник}
{103372}{}{Дружественный противник.}
# PE_PICKPOCKET
{103381}{}{Карманник}
{103382}{}{Ваши способности шарить по чужим карманам необыкновенно увеличиваются. Теперь вы можете не обращать внимание на такие мелочи, как направление взгляда и размер одежды вашего клиента.}
# PE_GHOST
{103391}{}{Привидение}
{103392}{}{Когда заходит солнце, или вы оказываетесь в плохо освещенном углу, то начинаете передвигаться бесшумно. Ваша способность Красться увеличивается на 20 процентов.}
# PE_CULT_OF_PERSONALITY
{103401}{}{Культ личности}
{103402}{}{Отныне ваша репутация в народе всегда будет положительной. Без этого, большая негативная репутация отрицательно влияла на ваши отношения с хорошими людьми. А с плохими соответственно позитивная.}
# PE_SCROUNGER
{103411}{}{Имплантант в коре головного мозга}
{103412}{}{В ваш мозг вшит специальный чип, который позволяет записывать информацию, анализируемую сетчаткой глаза. Он улучшает вашу память, но из-за этого страдает восприятие.}
# PE_EXPLORER
{103421}{}{Непоседа}
{103422}{}{Смысл жизни непоседы заключается в поисках новых, интересных мест, куда он сует свой нос. С этим бонусом ваши шансы найти нечто необычное увеличиваются.}
# PE_FLOWER_CHILD
{103431}{}{Паладин}
{103432}{}{Вы паладин Братства Стали. Каждый человек в Братстве знает, что вы не спасуете перед лицом опасности.}
# PE_PATHFINDER
{103441}{}{Следопыт}
{103442}{}{Следопыт всегда находит кратчайший путь до места назначения. С таким бонусом время ваших переходов по Карте Мира уменьшается на 25 процентов.}
# PE_ANIMAL_FRIEND
{103451}{}{Писарь}
{103452}{}{Вы писарь Братства Стали. Ваш авторитет в научных вопросах непререкаем. Это звание заставляет испытывать к вам уважение у интеллектуальных кругов Братства.}
# PE_SCOUT
{103461}{}{Скаут}
{103462}{}{Вы развили в себе полезное качество для выживания в суровой пустыне - теперь вы видите дальше других, на Карте Мира - по одной клетке в каждую сторону. Кроме того, вам проще будет обнаружить что-либо особенное.}
# PE_MYSTERIOUS_STRANGER
{103471}{}{Таинственный странник}
{103472}{}{Отныне и навеки с вами в бою всегда будет присутствовать таинственный незнакомец. Он будет помогать вам выкарабкаться из самых безнадежных ситуаций. Но если погибнет - замены не ждите.}
# PE_RANGER
{103481}{}{Рейнджер}
{103482}{}{Ваше умение Скитальца повышается на 15 процентов. Увеличивается вероятность избежать неприятных встреч в пустыне или наоборот - отыскать там нечто полезное.}
# PE_QUICK_POCKETS
{103491}{}{Оптимизация}
{103492}{}{Вам удалось рассовать свои вещи по карманам так, чтобы они всегда были под рукой. Теперь манипуляции с предметами в инвентаре стоят в два раза меньше.}
# PE_SMOOTH_TALKER
{103501}{}{Говорливость}
{103502}{}{Говорун успевает вставлять два слова там, где другие еле управляются с одним, даже если не понимает, о чем речь. Каждый уровень ваш Интеллект во время диалога будет расти на 1, вплоть до 10.}
# PE_SWIFT_LEARNER
{103511}{}{Самоучка}
{103512}{}{С таким бонусом вы поистине становитесь самоучкой, так как на каждом уровне вы будете получать добавочные 5 процентов за любой опыт. Незаменимо в самом начале игры.}
# PE_TAG
{103521}{}{Умение}
{103522}{}{Взяв данный бонус, вы можете выбрать какое-либо Умение дополнительно. Оно будет повышаться примерно в 2 раза быстрее.}
# PE_MUTATE
{103531}{}{Мутация!}
{103532}{}{Радиация пустыни изменила вас! Одно из ваших умений мутировало во что-то трудно выразимое словами...}
# PE_ADRENALINE_RUSH
{103801}{}{Выброс адреналина}
{103802}{}{Вас бьют, а вы крепчаете. Потеряв более половины всех своих жизней вы получаете плюс 1 к Силе.}
# PE_CAUTIOUS_NATURE
{103811}{}{Бдительность}
{103812}{}{Находясь в пустыне, вы ходите с оглядкой и не позволяете врагам подобраться к вам сзади. При определении положения ваше восприятие увеличивается на 3.}
# PE_COMPREHENSION
{103821}{}{Наблюдательность}
{103822}{}{При чтении вы обращаете особенное внимание на мелкие детали. Используя книги, вы получаете на 50 процентов больше очков Умений.}
# PE_DEMOLITION_EXPERT
{103831}{}{Эксперт подрывник}
{103832}{}{Когда речь заходит об обращении с взрывчаткой, вы настоящий профессионал. Ваши заряды всегда детонируют вовремя и причиняют больше разрушений.}
# PE_GAMBLER
{103841}{}{Игрок}
{103842}{}{Вы наизусть знаете правила всех азартных игр и приемы шулеров. Плюс 20 процентов к умению Игры.}
# PE_GAIN_STRENGTH
{103851}{}{Получить силу}
{103852}{}{Этот бонус повышает на одно очко вашу Силу.}
# PE_GAIN_PERCEPTION
{103861}{}{Получить восприятие}
{103862}{}{Этот бонус повышает на одно очко ваше Восприятие.}
# PE_GAIN_ENDURANCE
{103871}{}{Получить выносливость}
{103872}{}{Этот бонус повышает на одно очко вашу Выносливость.}
# PE_GAIN_CHARISMA
{103881}{}{Получить обаяние}
{103882}{}{Этот бонус повышает на одно очко ваше Обаяние.}
# PE_GAIN_INTELLIGENCE
{103891}{}{Получить интеллект}
{103892}{}{Этот бонус повышает на одно очко ваш Интеллект.}
# PE_GAIN_AGILITY
{103901}{}{Получить ловкость}
{103902}{}{Этот бонус повышает на одно очко вашу Ловкость.}
# PE_GAIN_LUCK
{103911}{}{Получить удачу}
{103912}{}{Этот бонус повышает на одно очко вашу Удачу.}
# PE_HARMLESS
{103921}{}{Безвредность}
{103922}{}{Ваш невинный вид позволяет вам куда успешнее красть у людей вещи. Вы получаете 40 процентов к умению Воровать.}
# PE_HERE_AND_NOW
{103931}{}{Прямо сейчас}
{103932}{}{Взяв себе этот бонус вы немедленно получаете еще один уровень опытности.}
# PE_HTH_EVADE
{103941}{}{Верткость}
{103942}{}{Если вы не держите в руках никаких предметов, каждое неистраченное очко действия дает вам плюс 2 и 1/12 от умения рукопашного боя к защите к концу хода.}
# PE_KAMA_SUTRA_MASTER
{103951}{}{Спец по камасутре}
{103952}{}{Когда речь идет о сексуальном удовлетворении, ваши знания поистине невероятны.}
# PE_KARMA_BEACON
{103961}{}{Маяк кармы}
{103962}{}{Ваша карма сияет в два раза ярче. К добру или к худу, но поведение встреченных вами людей учитывает это.}
# PE_LIGHT_STEP
{103971}{}{Легкие шаги}
{103972}{}{Вы ловки, удачливы и всегда настороже. Этот бонус уменьшает вдвое шансы на то, что поставленная на вас ловушка сработает.}
# PE_LIVING_ANATOMY
{103981}{}{Анатомия жизни}
{103982}{}{Вы хорошо представляете себе внутреннее строение живых существ, их силы и слабости. При атаке по ним вы наносите на 5 очков больше ущерба и получаете 10 процентов бонуса к умению Доктора.}
# PE_MAGNETIC_PERSONALITY
{103991}{}{Привлекательность}
{103992}{}{Вместе с вами может ходить еще один компаньон, но не забывайте, что больше пяти - это уже толпа.}
# PE_NEGOTIATOR
{104001}{}{Негоциант}
{104002}{}{Вы профессионально ведете переговоры и заключаете сделки. С этим бонусом вы можете попробовать договориться до чего угодно, имея плюс 10 процентов для Торговли и Разговора.}
# PE_PACK_RAT
{104011}{}{Запаковка}
{104012}{}{Умелое распределение вещей в инвентаре позволяет вам носить некоторое добавочное количество полезных предметов.}
# PE_PYROMANIAC
{104021}{}{Пироманьяк}
{104022}{}{Вы причиняете больше ущерба при стрельбе из огнеметов, и ваши враги сгорают в ужасных мучениях.}
# PE_QUICK_RECOVERY
{104031}{}{Прыгучесть}
{104032}{}{Если вас собьют с ног, вы быстрее поднимаетесь обратно.}
# PE_SALESMAN
{104041}{}{Продажа}
{104042}{}{Вы умеете продавать и покупать. С этим бонусом вы на 40 процентов повышаете свое умение Торговли.}
# PE_STONEWALL
{104051}{}{Человек-глыба}
{104052}{}{Вероятность того, что вас собьют с ног, сильно уменьшается.}
# PE_THIEF
{104061}{}{Вор}
{104062}{}{В ваших жилах течет кровь истинного вора. Получив этот бонус, вы повышаете на 10 процентов свои умения Красться, Взламывать замки, Воровать и работать с Ловушками.}
# PE_WEAPON_HANDLING
{104071}{}{Обращение с оружием}
{104072}{}{Вы можете носить оружие мощнее, чем остальные похожие на вас люди. Для этой цели ваша сила считается на 3 очка больше.}
# PE_VAULT_CITY_TRAINING
{104081}{}{Стажировка в Городе-Убежище}
{104082}{}{Вы прошли курс обучения медицине у лучших специалистов Города-Убежища.}
# PE_EXPERT_EXCREMENT
{104171}{}{Спец по уборке экскрементов}
{104172}{}{Вы научились убирать дерьмо за браминами лучше, чем кто-либо.}
# PE_JINXED_II
{104191}{}{Дурной глаз}
{104192}{}{Xорошая сторона дела заключается в том, что враги вокруг вас постоянно ошибаются. Плохо то, что вы ошибаетесь не меньше их!}
# PE_TERMINATOR
{104201}{}{Терминатор}
{104202}{}{Забудьте, что такое переломы конечностей, слепота и нокдауны! Титановый сплав, из которого сделан ваш скелет и жизненно важные органы, не помнется, даже если вас переедет танк. Все критические эффекты игнорируются.}
# PE_GECKO_SKINNING
{104301}{}{Скорняк}
{104302}{}{Вы освоили принципы разделки ящеров и легко обдираете их, чтобы получить ценные шкуры.}
# PE_VAULT_CITY_INOCULATIONS
{104311}{}{Прививки из Города-Убежища}
{104312}{}{Вы получили 10 процентов сопротивляемости к отравлению и радиации.}
# PE_DERMAL_IMPACT
{104321}{}{Подкожная броня}
{104322}{}{Вы имеете некоторую защиту от атак физического характера.}
# PE_DERMAL_IMPACT_ENH
{104331}{}{Улучшенная подкожная броня}
{104332}{}{Вы получили усиленную защиту от атак физического характера.}
# PE_PHOENIX_IMPLANTS
{104341}{}{Подкожная защита}
{104342}{}{Вы чуть реже подвергаетесь ущербу от энергетических атак.}
# PE_PHOENIX_IMPLANTS_ENH
{104351}{}{Улучшенная подкожная защита}
{104352}{}{Вы имеете большую дополнительную защиту против энергетических атак.}
# PE_NCR_PERCEPTION
{104361}{}{Операция доктора Клауса: Восприятие}
{104362}{}{После операции, проведенной Доктором Клаусом из НКР, ваше Восприятие повышено на одно очко.}
# PE_NCR_ENDURANCE
{104371}{}{Операция доктора Клауса: Выносливость}
{104372}{}{После операции, проведенной Доктором Клаусом из НКР, ваша Выносливость повышена на одно очко.}
# PE_NCR_BARTER
{104381}{}{Секреты мастерства: Бартер}
{104382}{}{Вы смогли многому научиться у торговцев НКР. Ваш навык бартера повышен на 5 очков.}
# PE_NCR_REPAIR
{104391}{}{Секреты мастерства: Ремонт}
{104392}{}{Механики НКР ознакомили вас с новой технологией починки оружия. Навык Ремонта повышен на 5 очков.}
# PE_VAMPIRE_ACCURACY
{104401}{}{Дитя полуночи}
{104402}{}{Сетчатка ваших глаз отличается повышенной чувствительностью  в ночное и сумеречное время. Вы хорошо видите в темноте, а значит, реже промахиваетесь. Неприятный сюрприз для тех, кто хочет напасть на вас ночью.}
# PE_VAMPIRE_REGENERATION
{104411}{}{Кровь Носферату}
{104412}{}{Плазма крови вашего тела подвеглась условно-положительной мутации. Теперь любые раны у вас заживают быстрее, чем раньше. Очень полезно в пустоши, где нет доктора.}


# 104700
# ADDICTION_NUKA_COLA, addictions
{104701}{}{Привыкание к Нюка-Коле}
{104702}{}{Вам хочется еще немножко Нюка-Колы.}
# ADDICTION_BUFFOUT, addictions
{104711}{}{Привыкание к Баффауту}
{104712}{}{У вас начались судороги.}
# ADDICTION_MENTATS, addictions
{104721}{}{Привыкание к Ментату}
{104722}{}{У вас кружится голова.}
# ADDICTION_PSYCHO, addictions
{104731}{}{Привыкание к Психо}
{104732}{}{Вы не ощущаете пространства.}
# ADDICTION_RADAWAY, addictions
{104741}{}{Привыкание к Рад Эвэй}
{104742}{}{Вас мучают приступы рвоты.}
# ADDICTION_JET, addictions
{104751}{}{Привыкание к Джету}
{104752}{}{Все вокруг вас движется так медленно... вам срочно надо занюхнуть еще немного Джета!}
# ADDICTION_TRAGIC, addictions
{104761}{}{Xобби Трагика}
{104762}{}{Вы страстно жаждете распаковать очередную коробку карт Трагика.}


# 104800
# KARMA_BERSERKER
{104801}{}{Берсеркер}
{104802}{}{Вы убили чрезвычайно много разных людей. Xотя за это обычно не очень-то любят, но зато боятся, а значит и уважают. С такой репутацией надо прямо сразу идти в бандиты.}
# KARMA_CHAMPION
{104811}{}{Правдоборец}
{104812}{}{Ваши действия прославили вас как защитника всех угнетенных, борца за счастье трудового народа. Всем известны ваша холодная голова, горячее сердце и чистые руки.}
# KARMA_CHILDKILLER
{104821}{}{Убийца детей}
{104822}{}{Вы убиваете маленьких, невинных детишек, надежду и будущее пустыни. Творимое вами зло не нравится никому. Это очень плохо.}
# KARMA_SEXPERT
{104831}{}{Сексперт}
{104832}{}{Вы понимаете секс. Вы умеете показать себя в постели с лучшей стороны, и это единственное место, где вы ведете себя безупречно.}
# KARMA_PRIZEFIGHTER
{104841}{}{Чемпион бокса}
{104842}{}{Схватки на ринге заслужили вам умение драться и титул первой перчатки Северной Калифорнии. Во всем нужна сноровка, закалка, тренировка, иначе вам удачи не видать!}
# KARMA_GIGOLO
{104851}{}{Спермотоксикоз}
{104852}{}{Посмотрим правде в глаза: Вы совокупляетесь с любым млекопитающим существом, ходящим на двух ногах. А иногда вы куда менее разборчивы...}
# KARMA_GRAVE_DIGGER
{104861}{}{Гробокопатель}
{104862}{}{Вашим лозунгом стала популярная присказка "Мертвые не кусаются". Страсть к раскопкам чужих могил и краже имущества покойных - ваше хобби.}
# KARMA_MARRIED
{104871}{}{Супружество}
{104872}{}{Поздравляем вас с успешным бракосочетанием. Теперь у вас появился спутник жизни.}
# KARMA_PORN_STAR
{104881}{}{Порнозвезда}
{104882}{}{Настал день, когда на мутном небосклоне Нью-Рено взошла новая звезда. Ваши сексуальные достоинства известны всему городу.}
# KARMA_SLAVER
{104891}{}{Работорговец}
{104892}{}{Вступление в Гильдию работорговцев навсегда изменило вашу жизнь. Татуировка на лбу говорит о вашей профессии лучше всяких слов.}
# KARMA_VIRGIN_WASTES
{104901}{}{Целомудрие}
{104902}{}{Шагая по колено в грязи, вы умудрились не запачкаться и сохранить свою чистоту в жестоком мире пустыни.}
# KARMA_MAN_SALVATORE
{104911}{}{Человек Сальваторе}
{104912}{}{Дон Сальваторе принял вас под свое покровительство. Это всем известно, мелкая шушера уважает вас, пальцы веером - ваш неотъемлемый атрибут.}
# KARMA_MAN_BISHOP
{104921}{}{Человек Бишопа}
{104922}{}{Мистер Бишоп принял вас под свое покровительство. Это всем известно, мелкая шушера уважает вас, пальцы веером - ваш неотъемлемый атрибут.}
# KARMA_MAN_MORDINO
{104931}{}{Человек Мордино}
{104932}{}{Дон Мордино принял вас под свое покровительство. Это всем известно, мелкая шушера уважает вас, пальцы веером - ваш неотъемлемый атрибут.}
# KARMA_MAN_WRIGHT
{104941}{}{Человек Райта}
{104942}{}{Клан Райтов принял вас под свое покровительство. Это всем известно, мелкая шушера уважает вас, пальцы веером - ваш неотъемлемый атрибут.}
# KARMA_SEPARATED
{104951}{}{В разводе}
{104952}{}{Увы и ах, но ваша любовная лодка разбилась о быт. Какое несчастье.}
# KARMA_PEDOBEAR
{104961}{}{Педобир}
{104962}{}{Ты трахнул невинное дитя. Как ты мог. Сволочь. Ты заработал себе неприятности на всю оставшуюся жизнь.}
# KARMA_VC_GUARDSMAN
{104971}{}{Гвардеец}
{104972}{}{Вы гвардеец Города-убежища, гордость и краса вооруженных сил. Вы можете носить одежду форменных цветов. Вам даже немного стыдно вашей собственной улётности и неотразимости.}


# 105000
# DAMAGE_POISONED, damages
{105001}{}{Отравление}
{105002}{}{Ваш персонаж находится под воздействием яда. Это будет отнимать очки жизней, пока вы не вылечитесь или яд не выйдет из организма.}
# DAMAGE_RADIATED, damages
{105011}{}{Облучение}
{105012}{}{Ваш персонаж находится под воздействием поражающего эффекта радиации. Чем сильнее было облучение, тем хуже будет дальнейшая жизнь героя.}
# DAMAGE_EYE, damages
{105021}{}{Ранение в глаз}
{105022}{}{Ваш персонаж был серьезно ранен в один или оба глаза, теперь его Восприятие понизится. Особо уже не присмотришься.}
# DAMAGE_RIGHT_ARM, damages
{105031}{}{Сломана прав. рука}
{105032}{}{Правая рука была сильно повреждена и теперь не двигается. Отныне вы не будете применять двуручное оружие. Если вам повредят и другую руку, вы вообще будете воевать непонятно как. Разве только зубами.}
# DAMAGE_LEFT_ARM, damages
{105041}{}{Сломана левая рука}
{105042}{}{Левая рука была сильно повреждена и теперь не двигается. Отныне вы не будете применять двуручное оружие. Если вам повредят и другую руку, вы вообще будете воевать непонятно как. Разве только зубами.}
# DAMAGE_RIGHT_LEG, damages
{105051}{}{Сломана прав. нога}
{105052}{}{Ваш персонаж сильно охромел на правую ногу.}
# DAMAGE_LEFT_LEG, damages
{105061}{}{Сломана левая нога}
{105062}{}{Ваш персонаж сильно охромел на левую ногу.}


####################################################################################################################################
#
#		Traits (with TRAIT.MSG)
#
####################################################################################################################################

# 105500
# TRAIT_FAST_METABOLISM
{105501}{}{Быстрый метаболизм}
{105502}{}{Ваш уровень метаболизма вдвое превышает норму. Это означает, что вы будете менее устойчивы к воздействию радиации и ядов, но лечиться будете быстрее.}
# TRAIT_BRUISER
{105511}{}{Крушила}
{105512}{}{Двигаемся помедленнее, но зато повнушительнее. Бьем нечасто, но зато так, чтобы на всю жизнь запомнили! Количество ваших очков Действия уменьшается, но зато Сила увеличивается.}
# TRAIT_SMALL_FRAME
{105521}{}{Xилое тело}
{105522}{}{Вы не так велики, как окружающие, хотя это никогда вам особо не мешало. Вы не в состоянии таскать тяжелые грузы, зато более проворны.}
# TRAIT_ONE_HANDER
{105531}{}{Однорукий}
{105532}{}{Вы хорошо работаете только одной из рук. Благодаря этому вы неплохо владеете обычным оружием, но с двуручным начинаются проблемы.}
# TRAIT_FINESSE
{105541}{}{Точность}
{105542}{}{Все ваши атаки очень точны. Повреждения наносится поменьше, но при этом больше вероятность критического удара.}
# TRAIT_KAMIKAZE
{105551}{}{Камикадзе}
{105552}{}{В бою вы не обращаете внимания на окружающую обстановку и действуете напролом. Это снижает количество ваших очков брони вплоть до минимума, улучшает реакцию в бою.}
# TRAIT_HEAVY_HANDED
{105561}{}{Громила}
{105562}{}{Вы бьете сильно, но не очень точно. Жестокие удары причиняют огромные повреждения врагам, однако почти никогда не оказываются критическими для их состояния.}
# TRAIT_FAST_SHOT
{105571}{}{Быстрый стрелок}
{105572}{}{У вас нет времени для нормального прицеливания, поэтому стреляете наугад, лишь бы побыстрее. Для применения оружия вам требуется на одно очко действий меньше.}
# TRAIT_BLOODY_MESS
{105581}{}{Маньяк}
{105582}{}{По странной случайности, люди вокруг вас умирают страшной, мучительной смертью. Для них вы находите худший вариант кончины.}
# TRAIT_JINXED
{105591}{}{Дурной глаз}
{105592}{}{Xорошая сторона дела заключается в том, что ваши враги постоянно ошибаются. Плохо то, что вы ошибаетесь не меньше их!}
# TRAIT_GOOD_NATURED
{105601}{}{Добродушие}
{105602}{}{В детстве вы занимались тихими, размеренными занятиями и не делали зарядку. Ваши боевые умения меньше, чем у других, но зато Первая Помощь, Доктор, Беседа и Торговля заметно лучше.}
# TRAIT_CHEM_RELIANT
{105611}{}{Неуст. к химии}
{105612}{}{Вы легче попадаете в зависимость от химикалий. Вероятность привыкания к разным веществам вдвое больше, чем норма, правда, вы проще переносите их эффект.}
# TRAIT_CHEM_RESISTANT
{105621}{}{Уст. к химии}
{105622}{}{Xимикалии приносят вам только половину нормального эффекта, но вероятность привыкания также снижена на 50% от нормы.}
# TRAIT_SEX_APPEAL
{105631}{}{Сексуальность}
{105632}{}{Вы умеете "правильно" обходиться с людьми другого пола. Однако ваше стремление совращать всех попало, может раздражать окружающих.}
# TRAIT_SKILLED
{105641}{}{Умелец}
{105642}{}{Так как вы неустанно работали над собой и постоянно улучшали свои возможности, то начнете игру с улучшенными параметрами. С другой стороны, вы получаете меньше доп. умений - одно за каждые 4 уровня.}
# TRAIT_NIGHT_PERSON
{105651}{}{Ночная персона}
{105652}{}{Совы вроде вас просыпаются обычно тогда, когда солнце заходит за горизонт. Параметры Интеллекта и Восприятия увеличиваются на 1 в ночное время суток (от 18:01 до 06:00), и уменьшаются тоже на один утром (от 06:01 до 18:00).}
# TRAIT_GIFTED
{105661}{}{Талант}
{105662}{}{Вы очень одарены различными способностями и превосходите обычный уровень. Все ваши параметры больше на единицу, но вы теряете 10% для умений и получаете на 5 очков меньше за уровень.}


# Reputation groups
#105700
# REPUTATION_DEN
{105701}{}{Яма}
# REPUTATION_KLAMATH
{105711}{}{Кламат}
# REPUTATION_MODOC
{105721}{}{Модок}
# REPUTATION_VAULT_CITY
{105731}{}{Город Убежище}
# REPUTATION_GECKO
{105741}{}{Гекко}
# REPUTATION_BROKEN_HILLS
{105751}{}{Брокен Хиллс}
# REPUTATION_NEW_RENO
{105761}{}{Нью Рено}
# REPUTATION_SIERRA
{105771}{}{Cьерра}
# REPUTATION_VAULT15
{105781}{}{Убежище 15}
# REPUTATION_NCR
{105791}{}{НКР}
# REPUTATION_CATHEDRAL
{105801}{}{Собор}
# REPUTATION_MARIPOSA
{105811}{}{Военная база}
# REPUTATION_REDDING
{105821}{}{Реддинг}
# REPUTATION_SF
{105831}{}{Сан-Франциско}
# REPUTATION_NAVARRO
{105841}{}{Наварро}
# REPUTATION_ARROYO
{105851}{}{Арройо}
# REPUTATION_PRIMAL_TRIBE
{105861}{}{Примитивное племя}
# REPUTATION_RANGERS
{105871}{}{Рейнджеры}
# REPUTATION_VAULT13
{105881}{}{Убежище 13}
# REPUTATION_SACRAMENTO
{105891}{}{Сакраменто}

####################################################################################################################################
#
#		3d attributes
#
####################################################################################################################################

# Body types
{150100}{}{Нормальн.}
{150101}{}{Тощий}
{150102}{}{Сильный}
{150103}{}{Толстый}
{150104}{}{Скелет}

# Skin colors
{151000}{}{Белая 1}
{151001}{}{Белая 2}
{151002}{}{Белая 3}
{151003}{}{Черная 1}
{151004}{}{Черная 2}
{151005}{}{Черная 3}
{151006}{}{Коричн. 1}
{151007}{}{Коричн. 2}
{151008}{}{Коричн. 3}
{151009}{}{Красная 1}
{151010}{}{Красная 2}
{151011}{}{Красная 3}
{151012}{}{Смуглая 1}
{151013}{}{Смуглая 2}
{151014}{}{Смуглая 3}
{151015}{}{Желтая 1}
{151016}{}{Желтая 2}
{151017}{}{Желтая 3}

# Hair colors
{151199}{}{Цвет волос}
{151200}{}{Коричн.}
{151201}{}{Серо-кор.}
{151202}{}{Черный}
{151203}{}{Серо-черн.}
{151204}{}{Белый}
{151205}{}{Серо-бел.}
{151206}{}{Светлый}
{151207}{}{Серо-свет.}
{151208}{}{Красный}
{151209}{}{Серо-крас.}

# Hair male
{152000}{}{Нет}
{152010}{}{Афро}
{152020}{}{Лысый}
{152030}{}{Горшок}
{152040}{}{Венок}
{152050}{}{Стиляга}
{152060}{}{Длинные}
{152070}{}{Военная}
{152080}{}{Ирокез}
{152090}{}{Косы}
{152100}{}{Лохматый}
{152110}{}{Короткие}
{152120}{}{По плечо}

# Hair female
{152200}{}{Нет}
{152210}{}{Афро}
{152220}{}{Горшок}
{152230}{}{Улей}
{152240}{}{Бетти}
{152250}{}{Отвес}
{152260}{}{Узел}
{152270}{}{Средние}
{152280}{}{Длинные 1}
{152290}{}{Длинные 2}
{152300}{}{Длинные 3}
{152310}{}{Ирокез}
{152320}{}{Косы}
{152330}{}{Тянутые}
{152340}{}{Короткие}

# Mustache male
{153000}{}{Нет}
{153010}{}{Широкие}
{153020}{}{Фу Манчу}
{153030}{}{Козлиные}
{153040}{}{Дядя}
{153050}{}{Руль}
{153060}{}{Отшельник}
{153070}{}{Бараньи}
{153080}{}{Небольшие}
{153090}{}{Щетина}

# Mustache generic
{153200}{}{Щиток}

# Ponytail
{154000}{}{Нет}
{154010}{}{Широкая}
{154020}{}{Тонкая}

# Beard male
{155000}{}{Нет}
{155010}{}{Амиши}
{155020}{}{Широкая}
{155030}{}{Фу Манчу}
{155040}{}{Козлиная}
{155050}{}{Дядя}
{155060}{}{Отшельник}
{155070}{}{Щетина}

####################################################################################################################################
#
#		Misc2 values names (100000 + pid*10 + number of val)
#
####################################################################################################################################

{1001000}{}{Заряд}
{1001001}{}{}
{1001002}{}{}

####################################################################################################################################
#
#		Intellect words
#
####################################################################################################################################

{1999000000}{}{
я  моя
ты  твоя
вы  ваша
мы  наша
меня  мою
мне  моей
тебя  твою
сказал  сказать
скажу  сказать
скажи  сказать
убил  убивай
убили  убивай
убью  убивай
убей  убивай
украл  украсть
укради  украсть
своровал  украсть
своруй  украсть
воровать  красть
хочу  хотеть
хотел  хотеть
положил  положить
положи  положить
дал  давать
дай  давать
верни  вернуть
вернул  вернуть
верну  вернуть
отдай  отдать
отдал  отдать
отдам  отдать
могу  мочь
говорить  гварить
говорю  гварить
понимаю  понимать
они  их
думаю  думать
думайте  думать
думаем  думать
думай  думать
бежать  бечь
бегу  бечь
беги  бечь
бегите  бечь
бежим  бечь
побежал  бечь
побежали  бечь
идти  ити
идти  ходить
хожу  ходить
интеллект  ум
взял  взять
взяли  взять
возьми  взять
возьмите  взять
возьму  взять
возьмем  взять
злодей  плохой
злодей  злой
убийца  плохой
убийца  злой
бандит  плохой
бандит  злой
рейдер  плохой
рейдер  злой
злодеи  плохие
злодеи  злые
убийцы  плохие
убийцы  злые
бандиты  плохие
бандиты  злые
рейдеры  плохие
рейдеры  злые
брамин  му-му
брамины  му-му
коровы  му-му
корова  му-му
караван  корован
караваны  корованны
дерьмо  какашки
черт  шайтан
иду  ходить
иди  ходить
пошел  ходить
пошли  ходить
пойду  ходить
пойди  ходить
пришел  приходить
шел  ходил
присоединяйся  твоя ходить за моей
присоединись  твоя ходить за моей
присоединяйтесь  ваша ходить за нашей
присоединитесь  ваша ходить за нашей
присоединился  твоя ходить за моей
присоединяемся  наша ходить за вашей
присоединились  наша с вашей ходить
присоединяюсь  моя ходить за твоей
присоединюсь  моя ходить за твоей
научи  научай
научите  научайте
моего  мой
моих  мои
моего  мое
мою  мой
враг  плохой
враг  злой
враги  злые
друг  хороший
друг  приятный
друга  хорошево
друзья  други
друзья  хорошие
нормальный  хороший
нормальные  хорошие
привет  моя приветствует
здравствуй  моя здаровается
здравствуйте  моя здаровается
машина  би-бип
хамер  би-бип
джип  би-бип
оружие  пиу-пиу
you  u
are  r
i  me
want  wanting
why  y
could  was can
did  doed
into  in
had  haved
joing  go wiz mi
the
am
a
an
}

{1999000001}{}{
а  а
а  я
б  б
б  п
в  в
в  ф
г  в
г  г
г  х
г  к
д  д
д  т
е  е
е  э
е  ё
е  й
е  йэ
е  о
ё  ё
ё  е
ё  о
ё  йо
ж  ж
ж  з
з  з
з  с
з  ж
и  и
и  е
и  ы
й  й
й  е
й  и
к  к
к  г
л  л
л  р
м  м
н  н
о  а
о  ё
п  п
п  б
р  р
р  л
с  с
с  з
т  т
т  д
у  у
у  о
у  ю
ф  ф
ф  в
х  х
х  г
ц  ц
ц  тс
ч  ч
ш  ш
щ  щ
щ  шч
ъ
ы  ы
ы  и
ь
э  э
э  е
э  йе
ю  ю
ю  йу
ю  у
я  я
я  йа
я  а
a  a
b  b
c  c
c  k
d  d
e  e
f  f
f  v
f  w
g  g
g  j
h  h
i  i
j  j
j  g
k  k
k  q
l  l
m  m
n  n
o  o
p  p
q  q
r  r
s  s
t  t
u  u
v  v
v  f
v  w
w  w
w  v
w  f
x  x
x  ks
y  y
z  z
th  z
ing  in
}

####################################################################################################################################
#
#		Help
#
####################################################################################################################################

# F7 - Включить/выключить подсветку имен нпц.
# F9 - Включить/выключить трассировку траектории выстрела.

{2000000000}{}{
Горячие клавиши в игре:

F1 - Включить/выключить помощь.
F2 - Сохранить сообщения в файл.
F3 - Сохранить скриншот.
F4 - Вкл./Выкл. отображение панели ввода текста.
F5 - Вкл./Выкл. расширение окна сообщений.
F6 - Включить/выключить подсветку имен игроков.
F8 - Включить/выключить скроллинг карты мышкой (помогает в оконном режиме).
F12 - Сворачивание клиента.
Указатели - скроллинг карты.
Esc - меню.
Pause/Break - пунтосвитчер в командной строке.
<,> - Вращаться против часовой или по часовой стрелке.
Home - центрирование на персонаже (на карте и на глобале).
A - Атака.
G - Подобрать итем под ногами.
C - Персонаж.
I - Инвентарь.
P - Пипбой.
F - Фиксбой.
B - Переключение активных слотов.
M - Переключение меню мыши.
N - Переключение режима итема.
S - Панель навыков.
Z - Масштабирование карты.
1-8 - Выбор навыка.
? - Текущее игровое время.
+,- - Регулирование яркости.
Ctrl + +,- - Регулирование громкости звуков.
Shift + +,- - Регулирование громкости музыки.
Alt + +,- - Регулирование Sleep.

Команды для общения:
первый символ . или / потом:
к К s S - кричать,
ш Ш w W - шептать,
э Э e E - эмоция,
р Р r R - рация.
После пробел можно не ставить, а если и поставите, то он игнорируется.
Введите сообщение и нажмите Enter.

Так же возможна отправка сообщений с помощью:
Ctrl + Enter - крик,
Alt + Enter - шепот,
Shift + Enter - рация.
}

####################################################################################################################################
#
#		Credits
#
####################################################################################################################################

# # == "|0xff8c8c84 "
# @ == "|0xff706050 "
# normal == "|0xff907824 "

{2000001000}{}{35} # Speed
{2000001010}{}{
Under construction












Under construction









Under construction







Under construction









Under construction








Under construction















































Yes, is still Under construction
}
# Shift + Credits
{2000001020}{}{
Hello world!
}


